import { getAccess,listAccess } from './dispatch-store.mjs';
import { requireDispatchAccess,requireOperation,requireAdminPermission } from './dispatch-permissions.mjs';
import * as svc from './dispatch-service.mjs';
import { createDispatchSnapshot,restoreDispatchSnapshot,snapshots } from './dispatch-snapshots.mjs';
import { readAudit } from './dispatch-audit.mjs';
const opError=(e,res)=>{const code=String(e?.message||e?.code||'STORAGE_ERROR');const map={UNAUTHENTICATED:401,FORBIDDEN:403,INSUFFICIENT_PERMISSION:403,DISPATCH_ACCESS_DENIED:403,DISPATCH_PERSONNEL_REQUIRED:403,DISPATCH_PERSONNEL_NOT_FOUND:400,DISPATCH_MEMBER_NOT_FOUND:404,DISPATCH_MEMBER_A_NOT_ASSIGNED:409,DISPATCH_MEMBER_B_NOT_ASSIGNED:409,DISPATCH_SAME_UNIT:409,DISPATCH_UNIT_NOT_ACTIVE:409,DISPATCH_ASSIGNMENT_TARGET_REQUIRED:400,DISPATCH_INVALID_CODE:400,DISPATCH_INVALID_URL:400,DISPATCH_UNIT_REQUIRED:400,DISPATCH_UNIT_TYPE_INACTIVE:409,DISPATCH_VEHICLE_INACTIVE:409,DISPATCH_UNIT_INACTIVE:409,DISPATCH_REGION_INACTIVE:409,DISPATCH_LOCATION_INACTIVE:409,DISPATCH_RESTORE_CONFIRM_REQUIRED:400};let status=map[code]||500;if(String(e?.code)==='23505')status=409;if(String(e?.code)==='23503')status=409;if(String(e?.code)==='23514')status=400;console.error('Dispatch API error:',e);return res.status(status).json({error:code,retryable:status>=500})};
const asyncRoute=fn=>(req,res)=>Promise.resolve().then(()=>fn(req,res)).catch(e=>opError(e,res));
export function registerDispatchRoutes(app,{current,police}){const ctx=async req=>current(req);const access=async req=>{const c=await ctx(req);if(!c.x)return{c,access:null};return{c,access:await getAccess(c.x.id)}};
app.get('/api/dispatch/state',asyncRoute(async(req,res)=>{const {c,access:a}=await access(req);requireDispatchAccess(c,a);res.json(await svc.dispatchState(police))}));
app.get('/api/dispatch/activity',asyncRoute(async(req,res)=>{const {c,access:a}=await access(req);requireDispatchAccess(c,a);res.json({items:await readAudit({limit:req.query.limit,action:req.query.action,entityType:req.query.entityType})})}));
app.get('/api/dispatch/access',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_permissions');res.json({items:await listAccess()})}));
app.post('/api/dispatch/access',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_permissions');res.json({ok:true,item:await svc.setAccess(c,req.body?.discordId,req.body?.enabled!==false,req.body?.note||'',police)})}));
app.delete('/api/dispatch/access/:discordId',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_permissions');await svc.removeAccess(c,req.params.discordId);res.json({ok:true})}));
app.post('/api/dispatch/units',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_units');res.json({ok:true,item:await svc.createUnit(c,req.body||{},police)})}));
app.patch('/api/dispatch/units/:id',asyncRoute(async(req,res)=>{const {c,access:a}=await access(req);requireOperation(c,a);const admin=Boolean(c.admin&&c.permissions?.includes('manage_dispatch_units'));const body=admin?req.body||{}:{status:req.body?.status,vehicle_id:req.body?.vehicle_id,is_shared:req.body?.is_shared,map_position:req.body?.map_position,notes:req.body?.notes};res.json({ok:true,item:await svc.updateUnit(c,req.params.id,body)})}));
app.delete('/api/dispatch/units/:id',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_units');res.json({ok:true,item:await svc.deleteUnit(c,req.params.id)})}));
app.post('/api/dispatch/units/:id/members',asyncRoute(async(req,res)=>{const {c,access:a}=await access(req);requireOperation(c,a);res.json({ok:true,item:await svc.joinUnit(c,req.params.id,req.body?.discordId||c.x.id,police,req.body?.roleInUnit||'member')})}));
app.delete('/api/dispatch/units/:id/members/:discordId',asyncRoute(async(req,res)=>{const {c,access:a}=await access(req);requireOperation(c,a);res.json({ok:true,item:await svc.leaveUnit(c,req.params.id,req.params.discordId)})}));
app.post('/api/dispatch/swap',asyncRoute(async(req,res)=>{const {c,access:a}=await access(req);requireOperation(c,a);res.json({ok:true,item:await svc.swapUnitMembers(c,req.body?.memberA,req.body?.memberB)})}));
app.post('/api/dispatch/units/:id/assignments',asyncRoute(async(req,res)=>{const {c,access:a}=await access(req);requireOperation(c,a);res.json({ok:true,item:await svc.createAssignment(c,{...(req.body||{}),unit_id:req.params.id})})}));
app.patch('/api/dispatch/assignments/:id',asyncRoute(async(req,res)=>{const {c,access:a}=await access(req);requireOperation(c,a);res.json({ok:true,item:await svc.updateAssignment(c,req.params.id,req.body||{})})}));
app.delete('/api/dispatch/assignments/:id',asyncRoute(async(req,res)=>{const {c,access:a}=await access(req);requireOperation(c,a);res.json({ok:true,item:await svc.deleteAssignment(c,req.params.id)})}));
const struct=(perm,fn)=>asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,perm);res.json({ok:true,item:await fn(c,req)})});
app.post('/api/dispatch/regions',struct('manage_dispatch_regions',(c,r)=>svc.createRegion(c,r.body||{})));
app.patch('/api/dispatch/regions/:id',struct('manage_dispatch_regions',(c,r)=>svc.updateRegion(c,r.params.id,r.body||{})));
app.delete('/api/dispatch/regions/:id',struct('manage_dispatch_regions',(c,r)=>svc.archiveRegion(c,r.params.id)));
app.post('/api/dispatch/locations',struct('manage_dispatch_locations',(c,r)=>svc.createLocation(c,r.body||{})));
app.patch('/api/dispatch/locations/:id',struct('manage_dispatch_locations',(c,r)=>svc.updateLocation(c,r.params.id,r.body||{})));
app.delete('/api/dispatch/locations/:id',struct('manage_dispatch_locations',(c,r)=>svc.archiveLocation(c,r.params.id)));
app.post('/api/dispatch/unit-types',struct('manage_dispatch_types',(c,r)=>svc.createType(c,r.body||{})));
app.patch('/api/dispatch/unit-types/:id',struct('manage_dispatch_types',(c,r)=>svc.updateType(c,r.params.id,r.body||{})));
app.post('/api/dispatch/vehicles',struct('manage_dispatch_vehicles',(c,r)=>svc.createVehicle(c,r.body||{})));
app.patch('/api/dispatch/vehicles/:id',struct('manage_dispatch_vehicles',(c,r)=>svc.updateVehicle(c,r.params.id,r.body||{})));
app.delete('/api/dispatch/vehicles/:id',struct('manage_dispatch_vehicles',(c,r)=>svc.archiveVehicle(c,r.params.id)));
app.post('/api/dispatch/dispatchers',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_dispatchers');res.json({ok:true,item:await svc.assignDispatcher(c,req.body?.discordId,req.body?.note||'',police)})}));
app.patch('/api/dispatch/dispatchers/:id',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_dispatchers');res.json({ok:true,item:await svc.setDispatcherStatus(c,req.params.id,req.body?.status)})}));
app.delete('/api/dispatch/dispatchers/:id',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_dispatchers');res.json({ok:true,item:await svc.removeDispatcher(c,req.params.id)})}));
app.get('/api/dispatch/snapshots',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_snapshots');res.json({items:await snapshots()})}));
app.post('/api/dispatch/snapshots',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_snapshots');res.json({ok:true,item:await createDispatchSnapshot(c,req.body?.name,req.body?.description)})}));
app.post('/api/dispatch/snapshots/:id/restore',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_snapshots');if(req.body?.confirm!==true)throw new Error('DISPATCH_RESTORE_CONFIRM_REQUIRED');const result=await restoreDispatchSnapshot(c,req.params.id);res.json({ok:true,...result})}));
app.patch('/api/dispatch/settings',asyncRoute(async(req,res)=>{const c=await ctx(req);requireAdminPermission(c,'manage_dispatch_settings');res.json({ok:true,item:await svc.updateSettings(c,req.body||{})})}));
setInterval(()=>import('./dispatch-store.mjs').then(m=>m.cleanupAudit()).catch(e=>console.error('Dispatch audit cleanup failed:',e.message)),15*60*1000).unref?.();import('./dispatch-store.mjs').then(m=>m.cleanupAudit()).catch(()=>{});
}