import { getState,getAccess,listAccess,insert,update,remove,addMember,leaveMember,swapMembers } from './dispatch-store.mjs';
import { cleanRegion,cleanLocation,cleanType,cleanVehicle,cleanUnit,cleanAssignment } from './dispatch-validation.mjs';
import { recordAudit } from './dispatch-audit.mjs';
import { requireSupabase } from '../supabase.mjs';
async function personnelSet(policeFn){try{const rows=await policeFn();return new Map(rows.map(p=>[String(p.discordId),p]))}catch{throw new Error('DISPATCH_PERSONNEL_SOURCE_UNAVAILABLE')}}
async function activeRef(table,idValue,code){if(!idValue)return null;const {data,error}=await requireSupabase().from(table).select('id,active').eq('id',idValue).single();if(error)throw error;if(!data.active)throw new Error(code);return data}
export async function dispatchState(policeFn){const [state,access]=await Promise.all([getState(),listAccess()]);let personnel=[];try{personnel=await policeFn()}catch{}const people=new Map(personnel.map(p=>[String(p.discordId),p]));return{...state,access,people:personnel.map(p=>({discordId:String(p.discordId),name:p.name,rank:p.rank,department:p.department,status:p.status,code:p.code})),members:state.members.map(m=>({...m,personnel:people.get(String(m.discord_id))||null}))}}
export async function createUnit(ctx,body,policeFn){const people=await personnelSet(policeFn);const unit=cleanUnit(body,ctx.x.id,true);if(!unit.unit_code||!unit.type_id)throw new Error('DISPATCH_UNIT_REQUIRED');await activeRef('dispatch_unit_types',unit.type_id,'DISPATCH_UNIT_TYPE_INACTIVE');if(unit.vehicle_id)await activeRef('dispatch_vehicles',unit.vehicle_id,'DISPATCH_VEHICLE_INACTIVE');if(!people.has(String(ctx.x.id)))throw new Error('DISPATCH_PERSONNEL_REQUIRED');const row=await insert('dispatch_units',unit);await recordAudit(ctx,'UNIT_CREATED','unit',row.id,{},row);return row}
export async function updateUnit(ctx,id,body){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_units').select('*').eq('id',id).single();if(e)throw e;const cleaned=cleanUnit({...before,...body,id},ctx.x.id,false);await activeRef('dispatch_unit_types',cleaned.type_id,'DISPATCH_UNIT_TYPE_INACTIVE');if(cleaned.vehicle_id)await activeRef('dispatch_vehicles',cleaned.vehicle_id,'DISPATCH_VEHICLE_INACTIVE');const row=await update('dispatch_units',id,cleaned);await recordAudit(ctx,'UNIT_UPDATED','unit',id,before,row);return row}
export async function deleteUnit(ctx,id){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_units').select('*').eq('id',id).single();if(e)throw e;const {data:result,error}=await db.rpc('dispatch_delete_unit',{p_unit_id:String(id),p_actor:String(ctx.x.id)});if(error)throw error;await recordAudit(ctx,'UNIT_DELETED','unit',id,before,{...result,membersRemoved:Number(result?.membersRemoved||0),assignmentsRemoved:Number(result?.assignmentsRemoved||0)});return before}
export async function joinUnit(ctx,unitId,discordId,policeFn,roleInUnit='member'){const people=await personnelSet(policeFn);await activeRef('dispatch_units',unitId,'DISPATCH_UNIT_INACTIVE');const uid=String(discordId||ctx.x.id);if(!people.has(uid))throw new Error('DISPATCH_PERSONNEL_NOT_FOUND');const db=requireSupabase();const {data:row,error}=await db.rpc('dispatch_add_member',{p_unit_id:String(unitId),p_discord_id:uid,p_actor:String(ctx.x.id),p_role:String(roleInUnit||'member')});if(error)throw error;await recordAudit(ctx,'MEMBER_JOINED','unit',unitId,{},row);return row}
export async function leaveUnit(ctx,unitId,discordId){const row=await leaveMember(unitId,String(discordId||ctx.x.id));await recordAudit(ctx,'MEMBER_LEFT','unit',unitId,row,{});return row}
export async function swapUnitMembers(ctx,a,b){const result=await swapMembers(a,b,ctx.x.id);await recordAudit(ctx,'MEMBERS_SWAPPED','unit',`${result?.unitA||''}:${result?.unitB||''}`,{memberA:a,memberB:b},result||{});return result}
export async function createAssignment(ctx,body){const cleaned=cleanAssignment(body,ctx.x.id,true);await activeRef('dispatch_units',cleaned.unit_id,'DISPATCH_UNIT_INACTIVE');if(cleaned.region_id)await activeRef('dispatch_regions',cleaned.region_id,'DISPATCH_REGION_INACTIVE');if(cleaned.location_id){const location=await activeRef('dispatch_locations',cleaned.location_id,'DISPATCH_LOCATION_INACTIVE');const db=requireSupabase();const {data:loc,error}=await db.from('dispatch_locations').select('region_id').eq('id',location.id).single();if(error)throw error;if(cleaned.region_id&&loc?.region_id&&String(loc.region_id)!==String(cleaned.region_id))throw new Error('DISPATCH_LOCATION_REGION_MISMATCH');if(!cleaned.region_id&&loc?.region_id)cleaned.region_id=String(loc.region_id)}if(cleaned.assignment_type==='primary'){const db=requireSupabase();const {data:existing,error}=await db.from('dispatch_unit_assignments').select('*').eq('unit_id',cleaned.unit_id).eq('assignment_type','primary').eq('active',true);if(error)throw error;for(const item of existing||[]){const {data:closed,error:closeError}=await db.from('dispatch_unit_assignments').update({active:false,updated_by:String(ctx.x.id)}).eq('id',item.id).select('*').single();if(closeError)throw closeError;await recordAudit(ctx,'UNIT_ASSIGNMENT_REPLACED','assignment',item.id,item,closed)}}const row=await insert('dispatch_unit_assignments',cleaned);await recordAudit(ctx,'UNIT_ASSIGNMENT_CREATED','assignment',row.id,{},row);return row}
export async function updateAssignment(ctx,id,body){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_unit_assignments').select('*').eq('id',id).single();if(e)throw e;const cleaned=cleanAssignment({...before,...body,id},ctx.x.id,false);await activeRef('dispatch_units',cleaned.unit_id,'DISPATCH_UNIT_INACTIVE');if(cleaned.region_id)await activeRef('dispatch_regions',cleaned.region_id,'DISPATCH_REGION_INACTIVE');if(cleaned.location_id){const location=await activeRef('dispatch_locations',cleaned.location_id,'DISPATCH_LOCATION_INACTIVE');const {data:loc,error}=await db.from('dispatch_locations').select('region_id').eq('id',location.id).single();if(error)throw error;if(cleaned.region_id&&loc?.region_id&&String(loc.region_id)!==String(cleaned.region_id))throw new Error('DISPATCH_LOCATION_REGION_MISMATCH');if(!cleaned.region_id&&loc?.region_id)cleaned.region_id=String(loc.region_id)}const row=await update('dispatch_unit_assignments',id,cleaned);await recordAudit(ctx,'UNIT_ASSIGNMENT_UPDATED','assignment',id,before,row);return row}
export async function deleteAssignment(ctx,id){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_unit_assignments').select('*').eq('id',id).single();if(e)throw e;const row=await update('dispatch_unit_assignments',id,{active:false,updated_by:String(ctx.x.id)});await recordAudit(ctx,'UNIT_ASSIGNMENT_REMOVED','assignment',id,before,row);return row}
export async function createRegion(ctx,b){const row=await insert('dispatch_regions',cleanRegion(b,ctx.x.id,true));await recordAudit(ctx,'REGION_CREATED','region',row.id,{},row);return row}
export async function updateRegion(ctx,id,b){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_regions').select('*').eq('id',id).single();if(e)throw e;const row=await update('dispatch_regions',id,cleanRegion({...before,...b,id},ctx.x.id,false));await recordAudit(ctx,'REGION_UPDATED','region',id,before,row);return row}
export async function archiveRegion(ctx,id){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_regions').select('*').eq('id',id).single();if(e)throw e;const row=await update('dispatch_regions',id,{active:false,updated_by:String(ctx.x.id)});await recordAudit(ctx,'REGION_ARCHIVED','region',id,before,row);return row}
export async function createLocation(ctx,b){const row=await insert('dispatch_locations',cleanLocation(b,ctx.x.id,true));await recordAudit(ctx,'LOCATION_CREATED','location',row.id,{},row);return row}
export async function updateLocation(ctx,id,b){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_locations').select('*').eq('id',id).single();if(e)throw e;const row=await update('dispatch_locations',id,cleanLocation({...before,...b,id},ctx.x.id,false));await recordAudit(ctx,'LOCATION_UPDATED','location',id,before,row);return row}
export async function archiveLocation(ctx,id){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_locations').select('*').eq('id',id).single();if(e)throw e;const {data:result,error}=await db.rpc('dispatch_delete_location',{p_location_id:String(id),p_actor:String(ctx.x.id)});if(error)throw error;await recordAudit(ctx,'LOCATION_DELETED','location',id,before,{...result,deleted:true});return before}
export async function createType(ctx,b){const row=await insert('dispatch_unit_types',cleanType(b,ctx.x.id,true));await recordAudit(ctx,'UNIT_TYPE_CREATED','unit_type',row.id,{},row);return row}
export async function updateType(ctx,id,b){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_unit_types').select('*').eq('id',id).single();if(e)throw e;const row=await update('dispatch_unit_types',id,cleanType({...before,...b,id},ctx.x.id,false));await recordAudit(ctx,'UNIT_TYPE_UPDATED','unit_type',id,before,row);return row}
export async function createVehicle(ctx,b){const row=await insert('dispatch_vehicles',cleanVehicle(b,ctx.x.id,true));await recordAudit(ctx,'VEHICLE_CREATED','vehicle',row.id,{},row);return row}
export async function updateVehicle(ctx,id,b){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_vehicles').select('*').eq('id',id).single();if(e)throw e;const row=await update('dispatch_vehicles',id,cleanVehicle({...before,...b,id},ctx.x.id,false));await recordAudit(ctx,'VEHICLE_UPDATED','vehicle',id,before,row);return row}
export async function archiveVehicle(ctx,id){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_vehicles').select('*').eq('id',id).single();if(e)throw e;const {error:detachError}=await db.from('dispatch_units').update({vehicle_id:null,updated_by:String(ctx.x.id)}).eq('vehicle_id',id);if(detachError)throw detachError;const {error:deleteError}=await db.from('dispatch_vehicles').delete().eq('id',id);if(deleteError)throw deleteError;await recordAudit(ctx,'VEHICLE_DELETED','vehicle',id,before,{});return true}
export async function assignDispatcher(ctx,discordId,note='',policeFn){const people=await personnelSet(policeFn);const uid=String(discordId);if(!people.has(uid))throw new Error('DISPATCH_PERSONNEL_NOT_FOUND');const row=await insert('dispatch_dispatchers',{discord_id:uid,status:'active',started_at:new Date().toISOString(),assigned_by:String(ctx.x.id),note:String(note||'').slice(0,500)});await recordAudit(ctx,'DISPATCHER_ASSIGNED','dispatcher',row.id,{},row);return row}
export async function setDispatcherStatus(ctx,id,status){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_dispatchers').select('*').eq('id',id).single();if(e)throw e;const next=['active','offline'].includes(String(status))?String(status):'offline';const row=await update('dispatch_dispatchers',id,{status:next,ended_at:next==='offline'?new Date().toISOString():null});await recordAudit(ctx,next==='active'?'DISPATCHER_ACTIVATED':'DISPATCHER_OFFLINED','dispatcher',id,before,row);return row}
export async function removeDispatcher(ctx,id){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_dispatchers').select('*').eq('id',id).single();if(e)throw e;const {error}=await db.from('dispatch_dispatchers').delete().eq('id',id);if(error)throw error;await recordAudit(ctx,'DISPATCHER_REMOVED','dispatcher',id,before,{});return true}
export async function setAccess(ctx,discordId,enabled,note='',policeFn,permissions=[]){const people=await personnelSet(policeFn);const uid=String(discordId);if(!people.has(uid))throw new Error('DISPATCH_PERSONNEL_NOT_FOUND');const before=await getAccess(uid);const allowed=new Set(['view_dispatch','manage_dispatch_units','manage_dispatch_members','manage_dispatch_regions','manage_dispatch_locations','manage_dispatch_types','manage_dispatch_vehicles','view_dispatch_audit','manage_dispatch_dispatchers','manage_dispatch_snapshots','manage_dispatch_settings']);const perms=[...new Set((Array.isArray(permissions)?permissions:[]).map(String))].filter(x=>allowed.has(x));const db=requireSupabase();let row;if(before){const {data,error}=await db.from('dispatch_access').update({enabled:Boolean(enabled),permissions:perms,note:String(note||'').slice(0,500),updated_at:new Date().toISOString()}).eq('discord_id',uid).select('*').single();if(error)throw error;row=data}else row=await insert('dispatch_access',{discord_id:uid,enabled:Boolean(enabled),permissions:perms,granted_by:String(ctx.x.id),note:String(note||'').slice(0,500)});await recordAudit(ctx,enabled?'DISPATCH_ACCESS_GRANTED':'DISPATCH_ACCESS_REVOKED','access',uid,before||{},row);return row}
export async function removeAccess(ctx,discordId){const before=await getAccess(discordId);if(!before)return null;const db=requireSupabase();const {error}=await db.from('dispatch_access').delete().eq('discord_id',String(discordId));if(error)throw error;await recordAudit(ctx,'DISPATCH_ACCESS_REMOVED','access',discordId,before,{});return true}
export async function updateSettings(ctx,b){const db=requireSupabase();const {data:before,error:e}=await db.from('dispatch_settings').select('*').eq('id','default').single();if(e)throw e;const patch={};if(b.map_image_url!==undefined){const u=String(b.map_image_url||'').trim();try{const x=new URL(u);if(!['http:','https:'].includes(x.protocol))throw 0;patch.map_image_url=u}catch{throw new Error('DISPATCH_INVALID_URL')}}if(b.map_width!==undefined)patch.map_width=Math.max(100,Number(b.map_width)||806);if(b.map_height!==undefined)patch.map_height=Math.max(100,Number(b.map_height)||1000);if(b.poll_interval_ms!==undefined)patch.poll_interval_ms=Math.min(60000,Math.max(3000,Number(b.poll_interval_ms)||10000));patch.updated_by=String(ctx.x.id);const row=await update('dispatch_settings','default',patch);await recordAudit(ctx,'DISPATCH_SETTINGS_UPDATED','settings','default',before,row);return row}