import express from 'express';
import cookieParser from 'cookie-parser';
import jwt from 'jsonwebtoken';
import 'dotenv/config';
import { google } from 'googleapis';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.dirname(fileURLToPath(import.meta.url));
const app=express();
const PORT=Number(process.env.PORT||10000);
const DIST=path.resolve(root,'../dist');
const POLICE_SHEET_ID=process.env.GOOGLE_SHEET_ID||process.env.POLICE_SHEET_ID||'1J1cWiWn_yOhy3G7coTOwq6AoS9OZvW8rul1_gzZ8uRc';
const POLICE_RANGE=process.env.GOOGLE_SHEET_RANGE||process.env.POLICE_SHEET_RANGE||'officers!B4:H';
const DATA_SHEET_ID=process.env.ACADEMY_GOOGLE_SHEET_ID||process.env.GOOGLE_ACADEMY_DATA_SHEET_ID||'1s_VqyiWsFMQaLwemqhyqdzN8zB6lQa81NtF1-XvfuAk';
const DATA_SHEET=process.env.ACADEMY_GOOGLE_SHEET_NAME||process.env.GOOGLE_ACADEMY_DATA_SHEET_NAME||'DATA';
const SERVICE_FILE=process.env.GOOGLE_SERVICE_ACCOUNT_FILE||'/etc/secrets/google-service-account.json';
const CLIENT_ID=process.env.DISCORD_CLIENT_ID||'';
const CLIENT_SECRET=process.env.DISCORD_CLIENT_SECRET||'';
const REDIRECT=process.env.DISCORD_REDIRECT_URI||'http://localhost:10000/auth/discord/callback';
const FRONTEND=process.env.FRONTEND_URL||'/';
const INVITE=process.env.POLICE_DISCORD_INVITE_URL||'https://discord.gg/KWKcgDeJW3';
const SESSION_SECRET=String(process.env.SESSION_SECRET||'').trim();
if(!SESSION_SECRET||SESSION_SECRET.length<32)throw new Error('SESSION_SECRET is required and must be at least 32 characters.');
const ADMIN_IDS=new Set(String(process.env.ACADEMY_ADMIN_IDS||'').split(',').map(x=>x.replace(/\D/g,'')).filter(Boolean));
const PERMISSIONS={view_dashboard:'لوحة الإدارة',manage_members:'إدارة الأفراد',manage_applications:'إدارة التقديمات',manage_exams:'إدارة الاختبارات',manage_hierarchy:'إدارة الهيكل',view_evaluations:'الاطلاع على التقييمات',manage_evaluations:'إدارة التقييمات',manage_admins:'إدارة الأدمن',manage_settings:'الإعدادات'};
const ALL=Object.keys(PERMISSIONS);
const DEFAULT_HIERARCHY=[{id:'president',title:'رئيس الأكاديمية',name:'غير محدد',discordId:'',image:'',order:1},{id:'vice',title:'نائب رئيس الأكاديمية',name:'غير محدد',discordId:'',image:'',order:2},{id:'assistant',title:'مساعد نائب الرئيس',name:'غير محدد',discordId:'',image:'',order:3},{id:'commander',title:'قائد الشرطة',name:'غير محدد',discordId:'',image:'',order:4}];
const DEFAULT={version:21,settings:{academyName:'أكاديمية شرطة كيان',applicationsTitle:'التقديم الأولي للشرطة',applicationsDescription:'نموذج التقديم الرسمي للانضمام إلى شرطة كيان.',passingScore:60,logoUrl:'',policeInvite:INVITE},applicationQuestions:[],batches:[],applications:[],exams:[],examResults:[],examAttempts:[],evaluations:[],hierarchy:DEFAULT_HIERARCHY,admins:[],audit:[],memberImages:{}};
app.use(express.json({limit:'12mb'}));app.use(cookieParser());
let data=structuredClone(DEFAULT),sheets=null,credentials=null,storageReady=false,lastStorageError='',cache={at:0,rows:[]};
const id=v=>String(v??'').replace(/\D/g,'');
const norm=v=>String(v??'').trim().toLowerCase().replace(/[\s_\-#]+/g,'');
const now=()=>Date.now();
const validDate=v=>Boolean(v)&&Number.isFinite(new Date(v).getTime());
const state=(s,e)=>{const t=now(),a=validDate(s)?new Date(s).getTime():0,b=validDate(e)?new Date(e).getTime():0;if(a&&t<a)return'upcoming';if(b&&t>=b)return'ended';return'open'};
async function creds(){if(credentials)return credentials;const raw=String(process.env.GOOGLE_SERVICE_ACCOUNT_JSON||'').trim()||await fs.readFile(SERVICE_FILE,'utf8');return credentials=JSON.parse(raw)}
async function sheet(){if(sheets)return sheets;const auth=new google.auth.GoogleAuth({credentials:await creds(),scopes:['https://www.googleapis.com/auth/spreadsheets']});return sheets=google.sheets({version:'v4',auth})}
async function ensureData(){const s=await sheet();const meta=await s.spreadsheets.get({spreadsheetId:DATA_SHEET_ID,fields:'sheets.properties'});const exists=(meta.data.sheets||[]).some(x=>x.properties?.title===DATA_SHEET);if(!exists)await s.spreadsheets.batchUpdate({spreadsheetId:DATA_SHEET_ID,requestBody:{requests:[{addSheet:{properties:{title:DATA_SHEET}}}]}})}
async function save(){await ensureData();const s=await sheet();await s.spreadsheets.values.update({spreadsheetId:DATA_SHEET_ID,range:`${DATA_SHEET}!A1`,valueInputOption:'RAW',requestBody:{values:[[JSON.stringify(data)]]}});storageReady=true;lastStorageError=''}
async function load(){try{await ensureData();const s=await sheet();const r=await s.spreadsheets.values.get({spreadsheetId:DATA_SHEET_ID,range:`${DATA_SHEET}!A1`});const raw=r.data.values?.[0]?.[0];if(raw){const p=JSON.parse(raw);data={...structuredClone(DEFAULT),...p,settings:{...structuredClone(DEFAULT).settings,...(p.settings||{})},hierarchy:Array.isArray(p.hierarchy)?p.hierarchy:structuredClone(DEFAULT_HIERARCHY),applications:Array.isArray(p.applications)?p.applications:[],batches:Array.isArray(p.batches)?p.batches:[],exams:Array.isArray(p.exams)?p.exams:[],evaluations:Array.isArray(p.evaluations)?p.evaluations:[],admins:Array.isArray(p.admins)?p.admins:[],memberImages:p.memberImages||{}}}for(const uid of ADMIN_IDS)if(!data.admins.some(a=>id(a.discordId)===uid))data.admins.push({discordId:uid,name:'Super Admin',permissions:ALL,enabled:true,source:'environment',createdAt:new Date().toISOString()});await save();storageReady=true;console.log(`Google DATA storage ready (${DATA_SHEET})`)}catch(e){storageReady=false;lastStorageError=e.message;console.error('Google DATA storage unavailable:',e.message)}}
function headersIndex(h,names,f){const a=h.map(norm);for(const name of names){const x=norm(name),i=a.findIndex(v=>v===x||v.includes(x)||x.includes(v));if(i>=0)return i}return f}
function parseOfficer(h,r){const b=headersIndex(h,['Badge #','Badge','البادج','الكود'],0),n=headersIndex(h,['الاسم','name'],1),l=headersIndex(h,['الإجازة','الاجازة','leave'],2),k=headersIndex(h,['الرتبة','الرتبه','rank'],3),s=headersIndex(h,['الحالة','status'],4),q=headersIndex(h,['المسؤولية','المسؤوليه','responsibility'],5),d=headersIndex(h,['ديسكورد','discord','discord id','discordid','discord_id'],6);return{badge:String(r[b]??'').trim(),name:String(r[n]??'').trim(),leave:String(r[l]??'').trim(),rank:String(r[k]??'').trim(),status:String(r[s]??'').trim(),responsibility:String(r[q]??'').trim(),discordId:id(r[d])}}
async function police(force=false){if(!force&&cache.rows.length&&now()-cache.at<60000)return cache.rows;const s=await sheet();const r=await s.spreadsheets.values.get({spreadsheetId:POLICE_SHEET_ID,range:POLICE_RANGE});const v=r.data.values||[],rows=v.slice(1).map(x=>parseOfficer(v[0]||[],x)).filter(x=>x.discordId||x.name);if(!rows.length)throw new Error('POLICE_SHEET_EMPTY');cache={at:now(),rows};return rows}
function trainer(r){const t=norm(r?.rank);return ['رقيب','رقيبأول','مساعد','مساعدأول','ملازم','ملازماول','ملازمتاني','نقيب','رائد','مقدم','عقيد','عميد','لواء','فريق'].some(x=>t.includes(norm(x)))||String(r?.responsibility||'').includes('مدرب')}
function trainee(r){const t=norm(r?.rank);return ['مستجد','جندي','جنديأول'].some(x=>t===norm(x))}
function role(r){if(!r)return'citizen';if(trainer(r))return'trainer';return'officer'}
function session(req){try{return jwt.verify(req.cookies.kayan_session,SESSION_SECRET)}catch{return null}}
function admin(uid){return data.admins.find(a=>id(a.discordId)===id(uid))}
function perms(uid){return ADMIN_IDS.has(id(uid))?ALL:(admin(uid)?.enabled?(admin(uid).permissions||[]):[])}
async function current(req){const x=session(req);if(!x)return{x:null,police:null,admin:false,permissions:[]};const isAdmin=ADMIN_IDS.has(id(x.id))||Boolean(admin(x.id)?.enabled);try{const rows=await police();const p=rows.find(r=>id(r.discordId)===id(x.id))||null;return{x,police:p,role:role(p),admin:isAdmin,permissions:perms(x.id)}}catch(e){return{x,police:null,role:'unknown',admin:isAdmin,permissions:perms(x.id),sheetError:e.message}}}
async function guard(req,res,p){const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});if(!c.admin)return res.status(403).json({error:'FORBIDDEN'});if(!storageReady)return res.status(503).json({error:'ACADEMY_STORAGE_UNAVAILABLE'});if(p&&!c.permissions.includes(p))return res.status(403).json({error:'INSUFFICIENT_PERMISSION'});return c}
function audit(c,action,target,details=''){data.audit.unshift({id:`audit-${Date.now()}`,at:new Date().toISOString(),actorId:String(c.x.id),actorName:c.police?.name||c.x.username,action,target,details});data.audit=data.audit.slice(0,1000)}
function cleanQuestion(q){const type=['text','yesno','choice'].includes(q?.type)?q.type:'text';const options=Array.isArray(q?.options)?q.options.map((o,i)=>typeof o==='object'?{id:String(o.id||`opt-${Date.now()}-${i}`),text:String(o.text||'').trim()}:({id:`opt-${Date.now()}-${i}`,text:String(o).trim()})).filter(o=>o.text):[];let correct=q?.correct==null?'':String(q.correct);if(type==='choice'&&!options.some(o=>o.id===correct))correct='';if(type==='yesno'&&!['نعم','لا'].includes(correct))correct='';if(type==='text')correct='';return{id:String(q?.id||`q-${Date.now()}-${Math.random().toString(36).slice(2,7)}`),text:String(q?.text||'').trim(),type,options,correct,required:q?.required!==false,points:Math.max(1,Number(q?.points||1))}}
function publicQuestion(q){return{id:q.id,text:q.text,type:q.type,options:q.options||[],required:q.required!==false,points:q.points||1}}
function activeBatch(){return data.batches.find(b=>b.status==='open'&&state(b.startAt,b.endAt)==='open')||null}

app.get('/api/health',async(_,res)=>res.json({ok:true,storageReady,storageError:lastStorageError,academyDataSheetId:DATA_SHEET_ID,academyDataSheetName:DATA_SHEET,policeSheetId:POLICE_SHEET_ID,discordConfigured:Boolean(CLIENT_ID&&CLIENT_SECRET)}));
app.get('/auth/discord',(req,res)=>{if(!CLIENT_ID||!CLIENT_SECRET)return res.status(503).send('Discord OAuth is not configured.');const u=new URL('https://discord.com/oauth2/authorize');u.searchParams.set('client_id',CLIENT_ID);u.searchParams.set('response_type','code');u.searchParams.set('redirect_uri',REDIRECT);u.searchParams.set('scope','identify');res.redirect(u.toString())});
app.get('/auth/discord/callback',async(req,res)=>{try{const code=String(req.query.code||'');if(!code)throw new Error('Missing code');const body=new URLSearchParams({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:REDIRECT});const token=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const td=await token.json();if(!token.ok)throw new Error(td.error_description||'Discord token failed');const ur=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${td.access_token}`}});const u=await ur.json();if(!ur.ok)throw new Error('Discord identity failed');const signed=jwt.sign({id:String(u.id),username:u.username,global_name:u.global_name||'',avatar:u.avatar||''},SESSION_SECRET,{expiresIn:'7d'});res.cookie('kayan_session',signed,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*86400000});res.redirect(FRONTEND||'/')}catch(e){console.error(e);res.status(500).send('Discord login failed.')}});
app.post('/api/logout',(req,res)=>{res.clearCookie('kayan_session');res.json({ok:true})});
app.get('/api/me',async(req,res)=>{const c=await current(req);if(!c.x)return res.json({authenticated:false,permissions:{isCitizen:true,isOfficer:false,isAdmin:false}});if(c.sheetError&&!c.admin)return res.json({authenticated:true,identityPending:true,discord:c.x,permissions:{isCitizen:false,isOfficer:false,isAdmin:false,adminPermissions:[]}});const officer=Boolean(c.police);res.json({authenticated:true,discord:c.x,police:c.police||null,role:officer?c.role:'citizen',permissions:{isCitizen:!officer,isOfficer:officer,isAdmin:c.admin,adminPermissions:c.permissions,canViewEvaluations:Boolean(c.admin||trainer(c.police))}})});
app.get('/api/public/members',async(_,res)=>{try{const rows=await police();res.json({members:rows.map(r=>({...r,image:data.memberImages?.[r.discordId]||''}))})}catch(e){res.status(503).json({error:'POLICE_SHEET_UNAVAILABLE'})}});
app.get('/api/academy/members',async(req,res)=>{const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});try{res.json({members:(await police()).map(r=>({...r,image:data.memberImages?.[r.discordId]||''}))})}catch{res.status(503).json({error:'POLICE_SHEET_UNAVAILABLE'})}});
app.get('/api/public/hierarchy',(_,res)=>res.json({hierarchy:[...(data.hierarchy||[])].sort((a,b)=>(a.order||0)-(b.order||0))}));
app.get('/api/public/academy',async(req,res)=>{const c=await current(req);const open=activeBatch();const mine=c.x&&data.applications.find(a=>a.discordId===String(c.x.id)&&open&&a.batchId===open.id);res.json({settings:{...data.settings,policeInvite:data.settings.policeInvite||INVITE},batch:open?{id:open.id,name:open.name,startAt:open.startAt,endAt:open.endAt,state:state(open.startAt,open.endAt)}:null,application:{enabled:Boolean(open),title:data.settings.applicationsTitle,description:data.settings.applicationsDescription,questions:(data.applicationQuestions||[]).map(publicQuestion)},myApplication:mine||null})});
app.get('/api/public/exams',(_,res)=>res.json({exams:data.exams.filter(e=>e.active).map(e=>({...e,state:state(e.startAt,e.endAt),questions:e.questions.map(publicQuestion)}))}));
app.post('/api/application',async(req,res)=>{try{const open=activeBatch();if(!open)return res.status(409).json({error:'NO_OPEN_BATCH'});const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});const existing=data.applications.find(a=>a.discordId===String(c.x.id)&&a.batchId===open.id);if(existing)return res.status(409).json({error:'ALREADY_APPLIED'});const answers=req.body?.answers||{};const item={id:`app-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,discordId:String(c.x.id),discordName:c.x.global_name||c.x.username,batchId:open.id,answers,submittedAt:new Date().toISOString(),status:'pending'};data.applications.unshift(item);await save();res.json({ok:true,application:item})}catch(e){console.error(e);res.status(503).json({error:'STORAGE_ERROR'})}});
app.get('/api/admin/state',async(req,res)=>{const c=await guard(req,res,'view_dashboard');if(!c||res.headersSent)return;res.json({settings:data.settings,batches:data.batches,applications:data.applications,exams:data.exams,examResults:data.examResults,evaluations:data.evaluations,hierarchy:data.hierarchy,admins:data.admins,audit:data.audit})});
app.put('/api/admin/settings',async(req,res)=>{const c=await guard(req,res,'manage_settings');if(!c||res.headersSent)return;data.settings={...data.settings,...req.body};audit(c,'UPDATE_SETTINGS','settings');await save();res.json({ok:true,settings:data.settings})});
app.patch('/api/admin/evaluation-batch',async(req,res)=>{const c=await guard(req,res,'manage_evaluations');if(!c||res.headersSent)return;const batchId=String(req.body?.batchId||'');if(batchId&&!data.batches.some(b=>String(b.id)===batchId))return res.status(404).json({error:'BATCH_NOT_FOUND'});data.settings.evaluationBatchId=batchId||'';audit(c,'SET_EVALUATION_BATCH',batchId||'AUTO');await save();res.json({ok:true,evaluationBatchId:data.settings.evaluationBatchId})});
app.patch('/api/admin/member-image-link',async(req,res)=>{const c=await guard(req,res,'manage_members');if(!c||res.headersSent)return;const uid=String(req.body?.discordId||'').replace(/\D/g,'');if(!uid)return res.status(400).json({error:'INVALID_DISCORD_ID'});data.memberImages||={};data.memberImages[uid]=String(req.body?.image||'').trim();audit(c,'UPDATE_MEMBER_IMAGE',uid);await save();res.json({ok:true})});
app.patch('/api/member-image',async(req,res)=>{const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});const image=String(req.body?.image||'').trim();if(image.length>200000)return res.status(413).json({error:'IMAGE_TOO_LARGE'});data.memberImages||={};data.memberImages[String(c.x.id)]=image;await save();res.json({ok:true})});
app.post('/api/admin/evaluations/:id/review',async(req,res)=>{const c=await guard(req,res,'manage_evaluations');if(!c||res.headersSent)return;const e=data.evaluations.find(x=>x.id===req.params.id);if(!e)return res.status(404).json({error:'EVALUATION_NOT_FOUND'});e.reviewStatus=String(req.body?.status||'reviewed');e.reviewedAt=new Date().toISOString();e.reviewedBy=String(c.x.id);audit(c,'REVIEW_EVALUATION',e.id,e.reviewStatus);await save();res.json({ok:true,evaluation:e})});
app.use(express.static(DIST));
app.get('*',(req,res)=>res.sendFile(path.join(DIST,'index.html')));
await load();
app.listen(PORT,'0.0.0.0',()=>console.log(`Kayan Police Academy listening on ${PORT}`));

// Expose the initialized server state to post-bootstrap feature modules.
// index.mjs imports this module first, then injects these references into globalThis.
export { app, data };
