import express from 'express';
import cookieParser from 'cookie-parser';
import jwt from 'jsonwebtoken';
import 'dotenv/config';
import { google } from 'googleapis';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const DIST_DIR=path.resolve(__dirname,'../dist');
const DATA_FILE=path.resolve(__dirname,'academy-data.json');
const app=express();
const PORT=Number(process.env.PORT||3001);
const SHEET_ID=process.env.GOOGLE_SHEET_ID||'1J1cWiWn_yOhy3G7coTOwq6AoS9OZvW8rul1_gzZ8uRc';
const SHEET_RANGE=process.env.GOOGLE_SHEET_RANGE||'A:Z';
const SHEETS_KEY=process.env.GOOGLE_SHEETS_API_KEY||'';
const SERVICE_JSON=process.env.GOOGLE_SERVICE_ACCOUNT_JSON||'';
const DATA_SHEET=process.env.GOOGLE_ACADEMY_DATA_SHEET_NAME||'ACADEMY_DATA';
const DISCORD_CLIENT_ID=process.env.DISCORD_CLIENT_ID||'';
const DISCORD_CLIENT_SECRET=process.env.DISCORD_CLIENT_SECRET||'';
const DISCORD_REDIRECT_URI=process.env.DISCORD_REDIRECT_URI||'http://localhost:3001/auth/discord/callback';
const FRONTEND_URL=process.env.FRONTEND_URL||'/';
const SESSION_SECRET=process.env.SESSION_SECRET||'CHANGE_ME';
const ENV_ADMIN_IDS=new Set(String(process.env.ACADEMY_ADMIN_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));
const SYNC_TTL=Number(process.env.SHEET_SYNC_TTL_MS||30000);
const DEFAULT_HIERARCHY=[{id:'president',title:'رئيس الأكاديمية',name:'غير محدد',discordId:'',image:''},{id:'vice',title:'نائب رئيس الأكاديمية',name:'غير محدد',discordId:'',image:''},{id:'assistant',title:'مساعد نائب الرئيس',name:'غير محدد',discordId:'',image:''},{id:'commander',title:'قائد الشرطة',name:'غير محدد',discordId:'',image:''}];
const DEFAULT_DATA={version:4,settings:{academyName:'أكاديمية شرطة كيان',applicationEnabled:false,applicationsTitle:'التقديم الأولي للشرطة',applicationsDescription:'نموذج التقديم الرسمي للانضمام إلى شرطة كيان.',passingScore:60},applicationQuestions:[],batches:[],applications:[],exams:[],examResults:[],hierarchy:DEFAULT_HIERARCHY,admins:[],audit:[]};
app.use(express.json({limit:'8mb'}));app.use(cookieParser());
let data=structuredClone(DEFAULT_DATA),sheetCache={at:0,rows:[]},sheetsClient=null;
const norm=v=>String(v??'').trim().toLowerCase().replace(/[\s_\-#]+/g,'');
const normalizeId=v=>String(v??'').replace(/\D/g,'');
const headerIndex=(headers,candidates,fallback=-1)=>{const h=headers.map(norm);for(const c of candidates){const i=h.findIndex(x=>x===norm(c)||x.includes(norm(c))||norm(c).includes(x));if(i>=0)return i}return fallback};
function rowToRecord(headers,row){const badgeI=headerIndex(headers,['Badge #','Badge','البادج','الكود','code'],1),nameI=headerIndex(headers,['الاسم','name','اسم'],2),leaveI=headerIndex(headers,['الإجازة','الاجازة','leave'],3),rankI=headerIndex(headers,['الرتبة','الرتبه','rank'],4),statusI=headerIndex(headers,['الحالة','status'],5),responsibilityI=headerIndex(headers,['المسؤولية','المسؤوليه','responsibility'],6),discordI=headerIndex(headers,['ديسكورد','discord','discord id','discordid'],7);return{badge:String(row[badgeI]??'').trim(),code:String(row[badgeI]??'').trim(),name:String(row[nameI]??'').trim(),leave:String(row[leaveI]??'').trim(),rank:String(row[rankI]??'').trim(),status:String(row[statusI]??'').trim().toUpperCase(),responsibility:String(row[responsibilityI]??'').trim(),discordId:normalizeId(row[discordI]),raw:Object.fromEntries(headers.map((h,i)=>[h||`column_${i+1}`,row[i]??'']))}};
async function readPoliceSheet(force=false){if(!force&&sheetCache.rows.length&&Date.now()-sheetCache.at<SYNC_TTL)return sheetCache.rows;let values=[];const s=service();if(s){const r=await s.spreadsheets.values.get({spreadsheetId:SHEET_ID,range:SHEET_RANGE});values=r.data.values||[]}else{if(!SHEETS_KEY)throw Error('Google Sheets access is not configured');const u=new URL(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent(SHEET_RANGE)}`);u.searchParams.set('key',SHEETS_KEY);const r=await fetch(u);if(!r.ok)throw Error(`Google Sheets API returned ${r.status}`);values=(await r.json()).values||[]}const headers=values[0]||[];sheetCache={at:Date.now(),rows:values.slice(1).map(row=>rowToRecord(headers,row)).filter(x=>x.discordId||x.name)};return sheetCache.rows}
function service(){if(!SERVICE_JSON)return null;if(sheetsClient)return sheetsClient;const credentials=JSON.parse(SERVICE_JSON);const auth=new google.auth.GoogleAuth({credentials,scopes:['https://www.googleapis.com/auth/spreadsheets']});sheetsClient=google.sheets({version:'v4',auth});return sheetsClient}
async function ensureDataSheet(s){const meta=await s.spreadsheets.get({spreadsheetId:SHEET_ID,fields:'sheets.properties'});if(!(meta.data.sheets||[]).some(x=>x.properties?.title===DATA_SHEET))await s.spreadsheets.batchUpdate({spreadsheetId:SHEET_ID,requestBody:{requests:[{addSheet:{properties:{title:DATA_SHEET}}}]}})}
async function loadData(){try{const s=service();if(s){await ensureDataSheet(s);const r=await s.spreadsheets.values.get({spreadsheetId:SHEET_ID,range:`${DATA_SHEET}!A1`});if(r.data.values?.[0]?.[0])data={...structuredClone(DEFAULT_DATA),...JSON.parse(r.data.values[0][0])};return}}catch(e){console.warn('Cloud academy storage unavailable:',e.message)}try{data={...structuredClone(DEFAULT_DATA),...JSON.parse(await fs.readFile(DATA_FILE,'utf8'))}}catch{data=structuredClone(DEFAULT_DATA)}}
async function saveData(){const payload=JSON.stringify(data);try{const s=service();if(s){await ensureDataSheet(s);await s.spreadsheets.values.update({spreadsheetId:SHEET_ID,range:`${DATA_SHEET}!A1`,valueInputOption:'RAW',requestBody:{values:[[payload]]}});return}}catch(e){console.warn('Cloud academy save failed, using local fallback:',e.message)}await fs.writeFile(DATA_FILE,JSON.stringify(data,null,2),'utf8')}
function deriveRole(rec){if(!rec)return'citizen';const text=`${rec.rank} ${rec.responsibility}`.toLowerCase();if(text.includes('رئيس الأكاديمية'))return'academy_president';if(text.includes('نائب رئيس الأكاديمية'))return'academy_vice_president';if(text.includes('مساعد نائب'))return'academy_assistant_vice';if(text.includes('قائد الشرطة'))return'police_commander';if(text.includes('شؤون'))return'affairs';if(text.includes('مدرب'))return'trainer';return'officer'}
function session(req){try{return jwt.verify(req.cookies.kayan_session,SESSION_SECRET)}catch{return null}}
function findAdmin(id){return data.admins.find(a=>String(a.discordId)===String(id))}
async function current(req){const x=session(req);if(!x)return{x:null,police:null,role:'citizen',admin:false,adminRecord:null};let rows=[];try{rows=await readPoliceSheet()}catch(e){console.warn('Police sheet:',e.message)}const police=rows.find(r=>normalizeId(r.discordId)===normalizeId(x.id))||null;const adminRecord=findAdmin(x.id);const admin=ENV_ADMIN_IDS.has(String(x.id))||Boolean(adminRecord?.enabled);return{x,police,role:deriveRole(police),admin,adminRecord}}
async function requireAdmin(req,res){const c=await current(req);if(!c.x||!c.admin){res.status(403).json({error:'FORBIDDEN'});return null}return c}
function audit(c,action,target,details=''){data.audit.unshift({id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,at:new Date().toISOString(),actorId:String(c.x.id),actorName:c.police?.name||c.x.global_name||c.x.username,action,target,details});data.audit=data.audit.slice(0,1000)}
app.get('/api/health',(_q,res)=>res.json({ok:true,sheetConfigured:Boolean(SHEETS_KEY||SERVICE_JSON),discordConfigured:Boolean(DISCORD_CLIENT_ID&&DISCORD_CLIENT_SECRET),persistentAcademyConfigured:Boolean(SERVICE_JSON),adminConfigured:ENV_ADMIN_IDS.size>0||data.admins.some(a=>a.enabled)}));
app.get('/api/me',async(req,res)=>{try{const c=await current(req);if(!c.x)return res.json({authenticated:false,role:'citizen',permissions:{isCitizen:true,isOfficer:false,isAdmin:false}});const officer=Boolean(c.police);res.json({authenticated:true,discord:c.x,police:c.police?{name:c.police.name,rank:c.police.rank,code:c.police.code,badge:c.police.badge,status:c.police.status,responsibility:c.police.responsibility,leave:c.police.leave,discordId:c.police.discordId}:null,role:officer?c.role:'citizen',permissions:{isCitizen:!officer,isOfficer:officer,isAdmin:c.admin,canViewEvaluations:c.admin||['academy_president','academy_vice_president','academy_assistant_vice','police_commander','affairs'].includes(c.role)}})}catch(e){res.status(503).json({error:e.message})}});
app.get('/api/public/hierarchy',(_q,res)=>res.json({hierarchy:data.hierarchy||DEFAULT_HIERARCHY}));
app.get('/api/public/academy',(_q,res)=>{const active=data.batches.find(b=>b.status==='open');res.json({settings:data.settings,application:{enabled:Boolean(data.settings.applicationEnabled),title:data.settings.applicationsTitle,description:data.settings.applicationsDescription,passingScore:data.settings.passingScore,questions:(data.applicationQuestions||[]).map(q=>({id:q.id,text:q.text,type:q.type,options:q.options||[],required:q.required!==false}))},batch:active?{id:active.id,name:active.name,openedAt:active.openedAt}:null})});
app.get('/api/public/exams',(_q,res)=>res.json({exams:data.exams.filter(e=>e.active).map(e=>({...e,questions:e.questions.map(q=>({id:q.id,text:q.text,type:q.type,options:q.options||[],required:q.required!==false}))}))}));
app.get('/api/academy/members',async(req,res)=>{const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});if(!c.police)return res.status(403).json({error:'OFFICER_ONLY'});try{const rows=await readPoliceSheet();res.json({members:rows.map(r=>({...r,role:deriveRole(r),admin:ENV_ADMIN_IDS.has(r.discordId)||Boolean(findAdmin(r.discordId)?.enabled)}))})}catch(e){res.status(503).json({error:e.message})}});
app.post('/api/applications',async(req,res)=>{const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});if(c.police)return res.status(403).json({error:'OFFICERS_CANNOT_APPLY'});const batch=data.batches.find(b=>b.status==='open');if(!data.settings.applicationEnabled||!batch)return res.status(409).json({error:'APPLICATIONS_CLOSED'});if(data.applications.some(a=>a.batchId===batch.id&&a.discordId===String(c.x.id)))return res.status(409).json({error:'ALREADY_SUBMITTED'});const answers=req.body?.answers&&typeof req.body.answers==='object'?req.body.answers:{};for(const q of data.applicationQuestions||[])if(q.required&&String(answers[q.id]??'').trim()==='')return res.status(400).json({error:'REQUIRED_QUESTION_MISSING',questionId:q.id});const item={id:`app-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,batchId:batch.id,discordId:String(c.x.id),name:c.x.global_name||c.x.username||'متقدم',submittedAt:new Date().toISOString(),status:'pending',answers};data.applications.unshift(item);await saveData();res.json({ok:true,application:item})});
app.post('/api/exams/:id/submit',async(req,res)=>{const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});const e=data.exams.find(x=>x.id===req.params.id&&x.active);if(!e)return res.status(404).json({error:'EXAM_NOT_FOUND'});const answers=req.body?.answers||{};let earned=0,total=0;for(const q of e.questions){const p=Number(q.points||1);total+=p;if(['choice','yesno'].includes(q.type)&&String(answers[q.id]??'')===String(q.correct??''))earned+=p}const score=total?Math.round(earned/total*100):0;const result={id:`result-${Date.now()}`,examId:e.id,userId:String(c.x.id),name:c.police?.name||c.x.global_name||c.x.username,score,passed:score>=Number(e.passingScore||60),submittedAt:new Date().toISOString()};data.examResults.unshift(result);await saveData();res.json({ok:true,result})});
app.get('/api/admin/state',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;let members=[];try{members=await readPoliceSheet()}catch{}res.json({settings:data.settings,applicationQuestions:data.applicationQuestions,batches:data.batches,applications:data.applications,exams:data.exams,examResults:data.examResults,hierarchy:data.hierarchy,admins:data.admins,audit:data.audit,members:members.map(r=>({...r,role:deriveRole(r)}))})});
app.put('/api/admin/settings',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;data.settings={...data.settings,applicationEnabled:Boolean(req.body?.applicationEnabled),applicationsTitle:String(req.body?.applicationsTitle||data.settings.applicationsTitle),applicationsDescription:String(req.body?.applicationsDescription||''),passingScore:Math.max(1,Math.min(100,Number(req.body?.passingScore||60)))};audit(c,'UPDATE_SETTINGS','academy');await saveData();res.json({ok:true,settings:data.settings})});
app.put('/api/admin/application',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;data.applicationQuestions=Array.isArray(req.body?.questions)?req.body.questions.map((q,i)=>({id:String(q.id||`q-${Date.now()}-${i}`),text:String(q.text||''),type:['choice','yesno','text'].includes(q.type)?q.type:'text',options:Array.isArray(q.options)?q.options.map(String):[],correct:q.correct==null?null:String(q.correct),required:q.required!==false,points:Number(q.points||1)})):[];audit(c,'UPDATE_APPLICATION','application',`${data.applicationQuestions.length} questions`);await saveData();res.json({ok:true,applicationQuestions:data.applicationQuestions})});
app.post('/api/admin/batches',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;const name=String(req.body?.name||'').trim();if(name.length<2)return res.status(400).json({error:'INVALID_BATCH_NAME'});if(data.batches.some(b=>b.status==='open'))return res.status(409).json({error:'BATCH_ALREADY_OPEN'});const batch={id:`batch-${Date.now()}`,name,status:'open',openedAt:new Date().toISOString(),closedAt:null,createdBy:String(c.x.id)};data.batches.unshift(batch);data.settings.applicationEnabled=true;audit(c,'CREATE_BATCH',batch.id,name);await saveData();res.json({ok:true,batch})});
app.patch('/api/admin/batches/:id',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;const b=data.batches.find(x=>x.id===req.params.id);if(!b)return res.status(404).json({error:'BATCH_NOT_FOUND'});const open=req.body?.status==='open';if(open&&data.batches.some(x=>x.status==='open'&&x.id!==b.id))return res.status(409).json({error:'ANOTHER_BATCH_OPEN'});b.status=open?'open':'closed';b.closedAt=open?null:new Date().toISOString();data.settings.applicationEnabled=open||data.batches.some(x=>x.status==='open');audit(c,open?'OPEN_BATCH':'CLOSE_BATCH',b.id,b.name);await saveData();res.json({ok:true,batch:b})});
app.patch('/api/admin/applications/:id',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;const a=data.applications.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'APPLICATION_NOT_FOUND'});const allowed=['pending','accepted','rejected','waitlist'];if(!allowed.includes(String(req.body?.status)))return res.status(400).json({error:'INVALID_STATUS'});a.status=req.body.status;a.reviewedAt=new Date().toISOString();a.reviewedBy=String(c.x.id);audit(c,'REVIEW_APPLICATION',a.id,a.status);await saveData();res.json({ok:true,application:a})});
app.post('/api/admin/exams',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;const b=req.body||{};const exam={id:`exam-${Date.now()}`,title:String(b.title||'اختبار جديد'),description:String(b.description||''),stage:String(b.stage||'عام'),passingScore:Number(b.passingScore||60),active:b.active!==false,createdAt:new Date().toISOString(),questions:Array.isArray(b.questions)?b.questions:[]};data.exams.unshift(exam);audit(c,'CREATE_EXAM',exam.id,exam.title);await saveData();res.json({ok:true,exam})});
app.put('/api/admin/exams/:id',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;const e=data.exams.find(x=>x.id===req.params.id);if(!e)return res.status(404).json({error:'EXAM_NOT_FOUND'});Object.assign(e,{title:String(req.body?.title||e.title),description:String(req.body?.description||''),stage:String(req.body?.stage||e.stage),passingScore:Number(req.body?.passingScore||e.passingScore),active:req.body?.active!==false,questions:Array.isArray(req.body?.questions)?req.body.questions:e.questions});audit(c,'UPDATE_EXAM',e.id,e.title);await saveData();res.json({ok:true,exam:e})});
app.delete('/api/admin/exams/:id',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;const before=data.exams.length;data.exams=data.exams.filter(x=>x.id!==req.params.id);if(before===data.exams.length)return res.status(404).json({error:'EXAM_NOT_FOUND'});audit(c,'DELETE_EXAM',req.params.id);await saveData();res.json({ok:true})});
app.post('/api/admin/hierarchy',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;const items=Array.isArray(req.body?.items)?req.body.items:[];data.hierarchy=items.slice(0,30).map((x,i)=>({id:String(x.id||`node-${Date.now()}-${i}`),title:String(x.title||'منصب'),name:String(x.name||'غير محدد'),discordId:normalizeId(x.discordId),image:String(x.image||'')}));audit(c,'UPDATE_HIERARCHY','hierarchy');await saveData();res.json({ok:true,hierarchy:data.hierarchy})});
app.post('/api/admin/admins',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;const id=normalizeId(req.body?.discordId);if(!id)return res.status(400).json({error:'INVALID_DISCORD_ID'});let a=findAdmin(id);if(a)Object.assign(a,{name:String(req.body?.name||a.name),permissions:Array.isArray(req.body?.permissions)?req.body.permissions:a.permissions,enabled:req.body?.enabled!==false});else{a={discordId:id,name:String(req.body?.name||''),permissions:Array.isArray(req.body?.permissions)?req.body.permissions:['view_dashboard'],enabled:true,createdAt:new Date().toISOString()};data.admins.push(a)}audit(c,'UPSERT_ADMIN',id,a.name);await saveData();res.json({ok:true,admin:a})});
app.patch('/api/admin/admins/:id',async(req,res)=>{const c=await requireAdmin(req,res);if(!c)return;const a=findAdmin(normalizeId(req.params.id));if(!a)return res.status(404).json({error:'ADMIN_NOT_FOUND'});if(req.body?.enabled!==undefined)a.enabled=Boolean(req.body.enabled);if(Array.isArray(req.body?.permissions))a.permissions=req.body.permissions;a.name=String(req.body?.name??a.name);audit(c,'UPDATE_ADMIN',a.discordId);await saveData();res.json({ok:true,admin:a})});
app.get('/auth/discord',(_q,res)=>{if(!DISCORD_CLIENT_ID||!DISCORD_CLIENT_SECRET)return res.status(503).send('Discord OAuth is not configured yet.');const p=new URLSearchParams({client_id:DISCORD_CLIENT_ID,response_type:'code',redirect_uri:DISCORD_REDIRECT_URI,scope:'identify'});res.redirect(`https://discord.com/oauth2/authorize?${p}`)});
app.get('/auth/discord/callback',async(req,res)=>{try{const code=String(req.query.code||'');if(!code)throw Error('Missing OAuth code');const body=new URLSearchParams({client_id:DISCORD_CLIENT_ID,client_secret:DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:DISCORD_REDIRECT_URI});const tr=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!tr.ok)throw Error('Discord token exchange failed');const tk=await tr.json();const mr=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${tk.access_token}`}});if(!mr.ok)throw Error('Discord identity lookup failed');const me=await mr.json();const token=jwt.sign({id:me.id,username:me.username,global_name:me.global_name,avatar:me.avatar},SESSION_SECRET,{expiresIn:'7d'});res.cookie('kayan_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.redirect(FRONTEND_URL||'/')}catch(e){res.status(500).send(`Discord login failed: ${e.message}`)}});
app.post('/api/logout',(_q,res)=>{res.clearCookie('kayan_session');res.json({ok:true})});
await loadData();
app.use(express.static(DIST_DIR,{index:'index.html'}));
app.use((req,res,next)=>{if(req.method!=='GET'||req.path.startsWith('/api/')||req.path.startsWith('/auth/'))return next();res.sendFile(path.join(DIST_DIR,'index.html'))});
app.listen(PORT,'0.0.0.0',()=>console.log(`Kayan Academy API: http://0.0.0.0:${PORT}`));