import express from 'express';
import cookieParser from 'cookie-parser';
import jwt from 'jsonwebtoken';
import 'dotenv/config';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),DIST_DIR=path.resolve(__dirname,'../dist');
const app=express(),PORT=Number(process.env.PORT||3001);
const SHEET_ID=process.env.GOOGLE_SHEET_ID||'1J1cWiWn_yOhy3G7coTOwq6AoS9OZvW8rul1_gzZ8uRc',SHEET_RANGE=process.env.GOOGLE_SHEET_RANGE||'A:Z',GOOGLE_SHEETS_API_KEY=process.env.GOOGLE_SHEETS_API_KEY||'';
const DISCORD_CLIENT_ID=process.env.DISCORD_CLIENT_ID||'',DISCORD_CLIENT_SECRET=process.env.DISCORD_CLIENT_SECRET||'',DISCORD_REDIRECT_URI=process.env.DISCORD_REDIRECT_URI||'http://localhost:3001/auth/discord/callback',FRONTEND_URL=process.env.FRONTEND_URL||'/',SESSION_SECRET=process.env.SESSION_SECRET||'CHANGE_ME';
const SYNC_TTL_MS=Number(process.env.SHEET_SYNC_TTL_MS||60000),ADMIN_IDS=new Set(String(process.env.ACADEMY_ADMIN_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));
app.use(express.json({limit:'3mb'}));app.use(cookieParser());let cache={at:0,rows:[]};const roleOverrides=new Map();
const hierarchy=[{id:'president',title:'رئيس الأكاديمية',name:'يحدد من لوحة الإدارة',discordId:'',image:''},{id:'vice',title:'نائب رئيس الأكاديمية',name:'يحدد من لوحة الإدارة',discordId:'',image:''},{id:'assistant',title:'مساعد نائب الرئيس',name:'يحدد من لوحة الإدارة',discordId:'',image:''},{id:'commander',title:'قائد الشرطة',name:'يحدد من لوحة الإدارة',discordId:'',image:''}];
const norm=v=>String(v??'').trim().toLowerCase().replace(/[\s_\-]+/g,'');const hi=(hs,cs,fb)=>{const n=hs.map(norm);for(const c of cs){const i=n.findIndex(h=>h.includes(norm(c)));if(i>=0)return i}return fb};
function rowToRecord(hs,row){const ni=hi(hs,['الاسم','name','اسم'],0),ri=hi(hs,['الرتبة','الرتبه','rank'],1),ci=hi(hs,['الكود','code'],2);return{name:String(row[ni]||'').trim(),rank:String(row[ri]||'').trim(),code:String(row[ci]||'').trim(),discordId:String(row[7]||'').trim(),raw:Object.fromEntries(hs.map((h,i)=>[h||`column_${i+1}`,row[i]??'']))}}
const safe=r=>r?{name:r.name,rank:r.rank,code:r.code,discordId:r.discordId}:null;
async function readSheet(){if(cache.rows.length&&Date.now()-cache.at<SYNC_TTL_MS)return cache.rows;if(!GOOGLE_SHEETS_API_KEY)throw Error('GOOGLE_SHEETS_API_KEY is not configured');const u=new URL(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent(SHEET_RANGE)}`);u.searchParams.set('key',GOOGLE_SHEETS_API_KEY);const r=await fetch(u);if(!r.ok)throw Error(`Google Sheets API returned ${r.status}`);const d=await r.json(),v=d.values||[],hs=v[0]||[];cache={at:Date.now(),rows:v.slice(1).map(x=>rowToRecord(hs,x)).filter(x=>x.discordId)};return cache.rows}
function role(rec){if(!rec)return'citizen';if(roleOverrides.has(rec.discordId))return roleOverrides.get(rec.discordId);const t=`${rec.rank} ${Object.values(rec.raw).join(' ')}`.toLowerCase();if(t.includes('رئيس الأكاديمية'))return'academy_president';if(t.includes('نائب رئيس الأكاديمية'))return'academy_vice_president';if(t.includes('مساعد نائب'))return'academy_assistant_vice';if(t.includes('قائد الشرطة'))return'police_commander';if(t.includes('شؤون'))return'affairs';if(t.includes('مدرب'))return'trainer';return'officer'}
function isAdmin(rec,id){return ADMIN_IDS.has(String(id))||['academy_president','academy_vice_president','academy_assistant_vice'].includes(role(rec))}
function perms(r,admin){const lead=['academy_president','academy_vice_president','academy_assistant_vice','police_commander'];return{isCitizen:r==='citizen',isOfficer:r!=='citizen',isTrainer:r==='trainer',isLeadership:lead.includes(r),isAffairs:r==='affairs',canApply:r==='citizen',canViewAcademy:r!=='citizen',canViewEvaluations:lead.includes(r)||r==='affairs'||admin,canManageAcademy:admin,isAdmin:admin}}
function session(req){try{return jwt.verify(req.cookies.kayan_session,SESSION_SECRET)}catch{return null}}
async function current(req){const x=session(req);if(!x)return{x:null,police:null,role:'citizen',admin:false};const rows=await readSheet(),police=rows.find(r=>r.discordId===String(x.id))||null,r=role(police);return{x,police,role:r,admin:isAdmin(police,x.id)}}
async function adminOnly(req,res){const c=await current(req);if(!c.admin){res.status(403).json({error:'ADMIN_ONLY'});return null}return c}
app.get('/api/health',(_q,s)=>s.json({ok:true,sheetConfigured:Boolean(GOOGLE_SHEETS_API_KEY),discordConfigured:Boolean(DISCORD_CLIENT_ID&&DISCORD_CLIENT_SECRET),adminConfigured:ADMIN_IDS.size>0}));
app.get('/api/me',async(q,s)=>{const c=await current(q);if(!c.x)return s.json({authenticated:false});return s.json({authenticated:true,discord:c.x,police:safe(c.police),role:c.role,permissions:perms(c.role,c.admin)})});
app.get('/api/academy/members',async(q,s)=>{const c=await current(q);if(!c.x)return s.status(401).json({error:'UNAUTHENTICATED'});if(c.role==='citizen')return s.status(403).json({error:'OFFICER_ONLY'});const rows=await readSheet();s.json({updatedAt:cache.at,members:rows.map(r=>({...safe(r),role:role(r),admin:isAdmin(r,r.discordId)}))})});
app.get('/api/admin/state',async(q,s)=>{const c=await adminOnly(q,s);if(!c)return;const rows=await readSheet();s.json({members:rows.map(r=>({...safe(r),role:role(r),admin:isAdmin(r,r.discordId)})),overrides:Object.fromEntries(roleOverrides),hierarchy})});
app.post('/api/admin/role',async(q,s)=>{const c=await adminOnly(q,s);if(!c)return;const id=String(q.body?.discordId||'').trim(),r=String(q.body?.role||'').trim(),allowed=['officer','trainer','affairs','academy_president','academy_vice_president','academy_assistant_vice','police_commander'];if(!id||!allowed.includes(r))return s.status(400).json({error:'INVALID_ROLE'});roleOverrides.set(id,r);s.json({ok:true})});
app.delete('/api/admin/role/:id',async(q,s)=>{const c=await adminOnly(q,s);if(!c)return;roleOverrides.delete(String(q.params.id));s.json({ok:true})});
app.post('/api/admin/hierarchy',async(q,s)=>{const c=await adminOnly(q,s);if(!c)return;const items=Array.isArray(q.body?.items)?q.body.items:[];if(items.length>12)return s.status(400).json({error:'TOO_MANY_ITEMS'});for(const x of items){if(x.image&&!(String(x.image).startsWith('data:image/png')||String(x.image).startsWith('https://')))return s.status(400).json({error:'PNG_OR_HTTPS_ONLY'});if(x.image&&String(x.image).length>2200000)return s.status(400).json({error:'IMAGE_TOO_LARGE'})}hierarchy.splice(0,hierarchy.length,...items.map((x,i)=>({id:String(x.id||`node-${i}`),title:String(x.title||'منصب'),name:String(x.name||'غير محدد'),discordId:String(x.discordId||''),image:String(x.image||'')})));s.json({ok:true,hierarchy})});
app.get('/auth/discord',(_q,s)=>{if(!DISCORD_CLIENT_ID)return s.status(503).send('Discord OAuth is not configured yet.');const p=new URLSearchParams({client_id:DISCORD_CLIENT_ID,response_type:'code',redirect_uri:DISCORD_REDIRECT_URI,scope:'identify'});s.redirect(`https://discord.com/oauth2/authorize?${p}`)});
app.get('/auth/discord/callback',async(q,s)=>{try{const code=String(q.query.code||'');const body=new URLSearchParams({client_id:DISCORD_CLIENT_ID,client_secret:DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:DISCORD_REDIRECT_URI});const tr=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!tr.ok)throw Error('Discord token exchange failed');const tk=await tr.json(),mr=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${tk.access_token}`}});if(!mr.ok)throw Error('Discord identity lookup failed');const me=await mr.json(),tok=jwt.sign({id:me.id,username:me.username,global_name:me.global_name,avatar:me.avatar},SESSION_SECRET,{expiresIn:'7d'});s.cookie('kayan_session',tok,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});s.redirect(FRONTEND_URL||'/')}catch(e){s.status(500).send(`Discord login failed: ${e.message}`)}});
app.post('/api/logout',(_q,s)=>{s.clearCookie('kayan_session');s.json({ok:true})});
app.use(express.static(DIST_DIR,{index:'index.html'}));app.use((req,res,next)=>{if(req.method!=='GET'||req.path.startsWith('/api/')||req.path.startsWith('/auth/'))return next();res.sendFile(path.join(DIST_DIR,'index.html'))});
app.listen(PORT,'0.0.0.0',()=>console.log(`Kayan Academy API: http://0.0.0.0:${PORT}`));
