import express from 'express';
import cookieParser from 'cookie-parser';
import jwt from 'jsonwebtoken';
import 'dotenv/config';
import { google } from 'googleapis';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST_DIR = path.resolve(__dirname, '../dist');
const DATA_FILE = path.resolve(__dirname, 'academy-data.json');
const app = express();
const PORT = Number(process.env.PORT || 3001);
const SHEET_ID = process.env.GOOGLE_SHEET_ID || '1J1cWiWn_yOhy3G7coTOwq6AoS9OZvW8rul1_gzZ8uRc';
const SHEET_RANGE = process.env.GOOGLE_SHEET_RANGE || 'A:Z';
const SHEETS_KEY = process.env.GOOGLE_SHEETS_API_KEY || '';
const SERVICE_JSON = process.env.GOOGLE_SERVICE_ACCOUNT_JSON || '';
const DATA_SHEET = process.env.GOOGLE_ACADEMY_DATA_SHEET_NAME || 'ACADEMY_DATA';
const DISCORD_CLIENT_ID = process.env.DISCORD_CLIENT_ID || '';
const DISCORD_CLIENT_SECRET = process.env.DISCORD_CLIENT_SECRET || '';
const DISCORD_REDIRECT_URI = process.env.DISCORD_REDIRECT_URI || 'http://localhost:3001/auth/discord/callback';
const FRONTEND_URL = process.env.FRONTEND_URL || '/';
const SESSION_SECRET = process.env.SESSION_SECRET || 'CHANGE_ME';
const ENV_ADMIN_IDS = new Set(String(process.env.ACADEMY_ADMIN_IDS || '').split(',').map(x => x.trim()).filter(Boolean));
const SYNC_TTL = Number(process.env.SHEET_SYNC_TTL_MS || 60000);
const ALL_PERMISSIONS = ['view_dashboard','manage_members','manage_roles','manage_admins','manage_trainers','view_evaluations','manage_evaluations','manage_hierarchy','manage_applications','manage_exams','view_audit','manage_settings'];
const PERMISSION_LABELS = {view_dashboard:'لوحة التحكم',manage_members:'إدارة الأفراد',manage_roles:'إدارة الرولات',manage_admins:'إدارة الأدمن',manage_trainers:'إدارة المدربين',view_evaluations:'الاطلاع على التقييمات',manage_evaluations:'إدارة التقييمات',manage_hierarchy:'إدارة هيكل الأكاديمية',manage_applications:'إدارة التقديمات',manage_exams:'إدارة الاختبارات',view_audit:'سجل العمليات',manage_settings:'إعدادات النظام'};
const DEFAULT_HIERARCHY = [{id:'president',title:'رئيس الأكاديمية',name:'يحدد من لوحة الإدارة',discordId:'',image:''},{id:'vice',title:'نائب رئيس الأكاديمية',name:'يحدد من لوحة الإدارة',discordId:'',image:''},{id:'assistant',title:'مساعد نائب الرئيس',name:'يحدد من لوحة الإدارة',discordId:'',image:''},{id:'commander',title:'قائد الشرطة',name:'يحدد من لوحة الإدارة',discordId:'',image:''}];
const DEFAULT_DATA = {version:3,application:{enabled:false,title:'التقديم الأولي للشرطة',description:'نموذج التقديم الرسمي للانضمام إلى شرطة كيان.',passingScore:60,questions:[]},batches:[],applications:[],exams:[],examResults:[],hierarchy:DEFAULT_HIERARCHY,admins:[],roleOverrides:{},audit:[]};
app.use(express.json({limit:'8mb'}));
app.use(cookieParser());
let sheetCache={at:0,rows:[]}; let data=structuredClone(DEFAULT_DATA); let sheetsClient=null;
const norm=v=>String(v??'').trim().toLowerCase().replace(/[\s_\-]+/g,'');
const headerIndex=(headers,candidates,fallback)=>{const h=headers.map(norm);for(const c of candidates){const i=h.findIndex(x=>x.includes(norm(c)));if(i>=0)return i}return fallback};
function rowToRecord(headers,row){const badgeI=headerIndex(headers,['badge #','badge','البادج','بادج','رقم البادج'],1),nameI=headerIndex(headers,['الاسم','name','اسم'],2),rankI=headerIndex(headers,['الرتبة','الرتبه','rank'],3),statusI=headerIndex(headers,['الحالة','status'],4),respI=headerIndex(headers,['المسؤولية','المسؤوليه','responsibility'],5),discordI=headerIndex(headers,['ديسكورد','discord id','discord','معرف الديسكورد'],7);return{badge:String(row[badgeI]||'').trim(),name:String(row[nameI]||'').trim(),rank:String(row[rankI]||'').trim(),status:String(row[statusI]||'').trim(),responsibility:String(row[respI]||'').trim(),discordId:String(row[discordI]||'').trim(),raw:Object.fromEntries(headers.map((h,i)=>[h||`column_${i+1}`,row[i]??'']))}}
async function readPoliceSheet(){if(sheetCache.rows.length&&Date.now()-sheetCache.at<SYNC_TTL)return sheetCache.rows;if(!SHEETS_KEY)throw Error('GOOGLE_SHEETS_API_KEY is not configured');const u=new URL(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${encodeURIComponent(SHEET_RANGE)}`);u.searchParams.set('key',SHEETS_KEY);const r=await fetch(u);if(!r.ok)throw Error(`Google Sheets API returned ${r.status}`);const d=await r.json(),v=d.values||[],headers=v[0]||[];sheetCache={at:Date.now(),rows:v.slice(1).map(r=>rowToRecord(headers,r)).filter(r=>r.discordId)};return sheetCache.rows}
function service(){if(!SERVICE_JSON)return null;if(sheetsClient)return sheetsClient;const credentials=JSON.parse(SERVICE_JSON);const auth=new google.auth.GoogleAuth({credentials,scopes:['https://www.googleapis.com/auth/spreadsheets']});sheetsClient=google.sheets({version:'v4',auth});return sheetsClient}
async function ensureDataSheet(s){const meta=await s.spreadsheets.get({spreadsheetId:SHEET_ID,fields:'sheets.properties'});const exists=(meta.data.sheets||[]).some(x=>x.properties?.title===DATA_SHEET);if(!exists)await s.spreadsheets.batchUpdate({spreadsheetId:SHEET_ID,requestBody:{requests:[{addSheet:{properties:{title:DATA_SHEET}}}]}})}
async function loadData(){try{const s=service();if(s){await ensureDataSheet(s);const r=await s.spreadsheets.values.get({spreadsheetId:SHEET_ID,range:`${DATA_SHEET}!A1`});if(r.data.values?.[0]?.[0]){data={...structuredClone(DEFAULT_DATA),...JSON.parse(r.data.values[0][0])};return}}}catch(e){console.warn('Academy cloud storage unavailable:',e.message)}try{data={...structuredClone(DEFAULT_DATA),...JSON.parse(await fs.readFile(DATA_FILE,'utf8'))}}catch{data=structuredClone(DEFAULT_DATA)}}
async function saveData(){const payload=JSON.stringify(data);try{const s=service();if(s){await ensureDataSheet(s);await s.spreadsheets.values.update({spreadsheetId:SHEET_ID,range:`${DATA_SHEET}!A1`,valueInputOption:'RAW',requestBody:{values:[[payload]]}});return}}catch(e){console.warn('Academy cloud save failed, using local fallback:',e.message)}await fs.writeFile(DATA_FILE,JSON.stringify(data,null,2),'utf8')}
function role(rec){if(!rec)return'citizen';if(data.roleOverrides?.[rec.discordId])return data.roleOverrides[rec.discordId];const t=`${rec.rank} ${rec.responsibility} ${Object.values(rec.raw||{}).join(' ')}`.toLowerCase();if(t.includes('رئيس الأكاديمية'))return'academy_president';if(t.includes('نائب رئيس الأكاديمية'))return'academy_vice_president';if(t.includes('مساعد نائب'))return'academy_assistant_vice';if(t.includes('قائد الشرطة'))return'police_commander';if(t.includes('شؤون'))return'affairs';if(t.includes('مدرب'))return'trainer';return'officer'}
function session(req){try{return jwt.verify(req.cookies.kayan_session,SESSION_SECRET)}catch{return null}}
async function adminEntry(id){return(data.admins||[]).find(a=>a.discordId===String(id)&&a.active)||null}
async function current(req){const x=session(req);if(!x)return{x:null,police:null,role:'citizen',admin:false,adminPerms:[]};let rows=[];try{rows=await readPoliceSheet()}catch(e){console.warn(e.message)}const police=rows.find(r=>r.discordId===String(x.id))||null;const envAdmin=ENV_ADMIN_IDS.has(String(x.id));const entry=await adminEntry(x.id);return{x,police,role:role(police),admin:envAdmin||!!entry,adminPerms:envAdmin?ALL_PERMISSIONS:(entry?.permissions||[])}}
async function requirePerm(req,res,p){const c=await current(req);if(!c.x||!c.admin||!c.adminPerms.includes(p)){res.status(403).json({error:'FORBIDDEN',permission:p});return null}return c}
function safe(r){return r?{badge:r.badge,name:r.name,rank:r.rank,status:r.status,responsibility:r.responsibility,discordId:r.discordId,raw:r.raw}:null}
const publicQuestions=qs=>(qs||[]).map(q=>({id:q.id,text:q.text,type:q.type,options:q.options||[],required:q.required!==false,points:q.points||1}));
function publicAcademy(){const active=data.batches.find(b=>b.status==='open');return{application:{enabled:Boolean(data.application.enabled),title:data.application.title,description:data.application.description,passingScore:data.application.passingScore,questions:publicQuestions(data.application.questions)},batch:active?{id:active.id,name:active.name,openedAt:active.openedAt}:null}}
function addAudit(c,action,target,meta={}){data.audit.unshift({id:`audit-${Date.now()}`,at:new Date().toISOString(),by:String(c.x.id),action,target,meta});data.audit=data.audit.slice(0,500)}
app.get('/api/health',(_q,s)=>s.json({ok:true,sheetConfigured:Boolean(SHEETS_KEY),discordConfigured:Boolean(DISCORD_CLIENT_ID&&DISCORD_CLIENT_SECRET),persistentAcademyConfigured:Boolean(SERVICE_JSON),adminConfigured:ENV_ADMIN_IDS.size>0||data.admins.some(x=>x.active)}));
app.get('/api/me',async(req,res)=>{try{const c=await current(req);if(!c.x)return res.json({authenticated:false});res.json({authenticated:true,discord:c.x,police:safe(c.police),role:c.role,permissions:{isCitizen:c.role==='citizen',isOfficer:c.role!=='citizen',isTrainer:c.role==='trainer',isLeadership:['academy_president','academy_vice_president','academy_assistant_vice','police_commander'].includes(c.role),isAffairs:c.role==='affairs',isAdmin:c.admin,isSuperAdmin:c.adminPerms.length===ALL_PERMISSIONS.length,adminPermissions:c.adminPerms,canViewEvaluations:c.admin||['academy_president','academy_vice_president','academy_assistant_vice','police_commander','affairs'].includes(c.role)}})}catch(e){res.status(503).json({error:e.message})}});
app.get('/api/public/hierarchy',(_q,res)=>res.json({hierarchy:data.hierarchy||DEFAULT_HIERARCHY}));
app.get('/api/public/academy',(_q,res)=>res.json(publicAcademy()));
app.get('/api/academy/members',async(req,res)=>{const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});if(c.role==='citizen'&&!c.admin)return res.status(403).json({error:'OFFICER_ONLY'});try{const rows=await readPoliceSheet();res.json({members:rows.map(r=>({...safe(r),role:role(r),admin:ENV_ADMIN_IDS.has(r.discordId)||!!data.admins.find(a=>a.discordId===r.discordId&&a.active)}))})}catch(e){res.status(503).json({error:e.message})}});
app.post('/api/applications',async(req,res)=>{const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});if(c.role!=='citizen')return res.status(403).json({error:'CITIZENS_ONLY'});const batch=data.batches.find(b=>b.status==='open');if(!data.application.enabled||!batch)return res.status(409).json({error:'APPLICATIONS_CLOSED'});if(data.applications.some(a=>a.batchId===batch.id&&a.discordId===String(c.x.id)))return res.status(409).json({error:'ALREADY_SUBMITTED'});const answers=req.body?.answers&&typeof req.body.answers==='object'?req.body.answers:{};for(const q of data.application.questions||[]){if(q.required&&String(answers[q.id]??'').trim()==='')return res.status(400).json({error:'REQUIRED_QUESTION_MISSING',questionId:q.id})}const item={id:`app-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,batchId:batch.id,discordId:String(c.x.id),name:c.police?.name||c.x.global_name||c.x.username||'متقدم',submittedAt:new Date().toISOString(),status:'pending',answers};data.applications.push(item);await saveData();res.json({ok:true,application:{id:item.id,batchId:item.batchId,status:item.status}})});
app.get('/api/admin/state',async(req,res)=>{const c=await requirePerm(req,res,'view_dashboard');if(!c)return;let rows=[];try{rows=await readPoliceSheet()}catch{}res.json({members:rows.map(r=>({...safe(r),role:role(r),admin:ENV_ADMIN_IDS.has(r.discordId)||!!data.admins.find(a=>a.discordId===r.discordId&&a.active)})),admins:data.admins,permissions:PERMISSION_LABELS,hierarchy:data.hierarchy,application:data.application,batches:data.batches,applications:data.applications,exams:data.exams,examResults:data.examResults,me:{permissions:c.adminPerms,isSuperAdmin:c.adminPerms.length===ALL_PERMISSIONS.length}})});
app.get('/api/admin/academy-state',async(req,res)=>{const c=await requirePerm(req,res,'view_dashboard');if(!c)return;res.json({application:data.application,batches:data.batches,applications:data.applications,hierarchy:data.hierarchy,exams:data.exams,examResults:data.examResults})});
app.post('/api/admin/admins',async(req,res)=>{const c=await requirePerm(req,res,'manage_admins');if(!c)return;const discordId=String(req.body?.discordId||'').trim(),name=String(req.body?.name||'').trim(),permissions=Array.isArray(req.body?.permissions)?req.body.permissions.filter(p=>ALL_PERMISSIONS.includes(p)):['view_dashboard'];if(!/^\d{5,25}$/.test(discordId))return res.status(400).json({error:'INVALID_DISCORD_ID'});if(discordId===String(c.x.id))return res.status(400).json({error:'CANNOT_RECREATE_SELF'});if(!permissions.every(p=>c.adminPerms.includes(p)))return res.status(403).json({error:'CANNOT_GRANT_UNOWNED_PERMISSION'});const existing=data.admins.find(a=>a.discordId===discordId);if(existing){existing.name=name||existing.name;existing.permissions=permissions;existing.active=true}else data.admins.push({discordId,name,permissions,active:true,createdBy:String(c.x.id),createdAt:new Date().toISOString()});addAudit(c,'admin.create',discordId);await saveData();res.json({ok:true,admins:data.admins})});
app.patch('/api/admin/admins/:id',async(req,res)=>{const c=await requirePerm(req,res,'manage_admins');if(!c)return;const a=data.admins.find(x=>x.discordId===String(req.params.id));if(!a)return res.status(404).json({error:'ADMIN_NOT_FOUND'});const permissions=Array.isArray(req.body?.permissions)?req.body.permissions.filter(p=>ALL_PERMISSIONS.includes(p)):a.permissions;if(!permissions.every(p=>c.adminPerms.includes(p)))return res.status(403).json({error:'CANNOT_GRANT_UNOWNED_PERMISSION'});a.name=String(req.body?.name??a.name);a.permissions=permissions;a.active=req.body?.active!==false;addAudit(c,'admin.update',a.discordId);await saveData();res.json({ok:true,admins:data.admins})});
app.delete('/api/admin/admins/:id',async(req,res)=>{const c=await requirePerm(req,res,'manage_admins');if(!c)return;if(String(req.params.id)===String(c.x.id))return res.status(400).json({error:'CANNOT_REMOVE_SELF'});const a=data.admins.find(x=>x.discordId===String(req.params.id));if(!a)return res.status(404).json({error:'ADMIN_NOT_FOUND'});a.active=false;addAudit(c,'admin.disable',a.discordId);await saveData();res.json({ok:true,admins:data.admins})});
app.post('/api/admin/role',async(req,res)=>{const c=await requirePerm(req,res,'manage_roles');if(!c)return;const id=String(req.body?.discordId||''),r=String(req.body?.role||''),allowed=['officer','trainer','affairs','academy_president','academy_vice_president','academy_assistant_vice','police_commander'];if(!id||!allowed.includes(r))return res.status(400).json({error:'INVALID_ROLE'});data.roleOverrides[id]=r;addAudit(c,'role.assign',id,{role:r});await saveData();res.json({ok:true,role:r})});
app.delete('/api/admin/role/:id',async(req,res)=>{const c=await requirePerm(req,res,'manage_roles');if(!c)return;delete data.roleOverrides[String(req.params.id)];addAudit(c,'role.remove',String(req.params.id));await saveData();res.json({ok:true})});
app.post('/api/admin/batches',async(req,res)=>{const c=await requirePerm(req,res,'manage_applications');if(!c)return;const name=String(req.body?.name||'').trim();if(name.length<2)return res.status(400).json({error:'INVALID_BATCH_NAME'});const open=data.batches.find(b=>b.status==='open');if(open)return res.status(409).json({error:'BATCH_ALREADY_OPEN',batch:open});const batch={id:`batch-${Date.now()}`,name,status:'open',openedAt:new Date().toISOString(),closedAt:null,createdBy:String(c.x.id)};data.batches.unshift(batch);data.application.enabled=true;addAudit(c,'batch.create',batch.id,{name});await saveData();res.json({ok:true,batch})});
app.patch('/api/admin/batches/:id',async(req,res)=>{const c=await requirePerm(req,res,'manage_applications');if(!c)return;const b=data.batches.find(x=>x.id===req.params.id);if(!b)return res.status(404).json({error:'BATCH_NOT_FOUND'});const status=req.body?.status==='open'?'open':'closed';if(status==='open'){const other=data.batches.find(x=>x.status==='open'&&x.id!==b.id);if(other)return res.status(409).json({error:'ANOTHER_BATCH_OPEN'});b.status='open';b.closedAt=null;data.application.enabled=true}else{b.status='closed';b.closedAt=new Date().toISOString();if(!data.batches.some(x=>x.status==='open'))data.application.enabled=false}addAudit(c,'batch.status',b.id,{status});await saveData();res.json({ok:true,batch:b})});
app.patch('/api/admin/applications/:id',async(req,res)=>{const c=await requirePerm(req,res,'manage_applications');if(!c)return;const a=data.applications.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'APPLICATION_NOT_FOUND'});const allowed=['pending','accepted','rejected','waitlist'],status=String(req.body?.status||'');if(!allowed.includes(status))return res.status(400).json({error:'INVALID_STATUS'});a.status=status;a.reviewedAt=new Date().toISOString();a.reviewedBy=String(c.x.id);addAudit(c,'application.review',a.id,{status});await saveData();res.json({ok:true,application:a})});
app.get('/api/admin/batches/:id/accepted',async(req,res)=>{const c=await requirePerm(req,res,'view_dashboard');if(!c)return;const batch=data.batches.find(x=>x.id===req.params.id);if(!batch)return res.status(404).json({error:'BATCH_NOT_FOUND'});res.json({batch,accepted:data.applications.filter(x=>x.batchId===batch.id&&x.status==='accepted')})});
app.put('/api/admin/application',async(req,res)=>{const c=await requirePerm(req,res,'manage_applications');if(!c)return;const b=req.body||{};data.application={enabled:b.enabled!==false,title:String(b.title||'التقديم الأولي للشرطة'),description:String(b.description||''),passingScore:Number(b.passingScore||60),questions:Array.isArray(b.questions)?b.questions.map((q,i)=>({id:String(q.id||`q-${Date.now()}-${i}`),text:String(q.text||''),type:['choice','yesno','text'].includes(q.type)?q.type:'text',options:Array.isArray(q.options)?q.options.map(String):[],correct:q.correct==null?null:String(q.correct),required:q.required!==false,points:Number(q.points||1)})):[]};addAudit(c,'application.settings','academy');await saveData();res.json({ok:true,application:data.application})});
app.post('/api/admin/hierarchy',async(req,res)=>{const c=await requirePerm(req,res,'manage_hierarchy');if(!c)return;const items=Array.isArray(req.body?.items)?req.body.items:[];data.hierarchy=items.slice(0,30).map((x,i)=>({id:String(x.id||`node-${Date.now()}-${i}`),title:String(x.title||'منصب'),name:String(x.name||'غير محدد'),discordId:String(x.discordId||''),image:String(x.image||'')}));addAudit(c,'hierarchy.update','academy');await saveData();res.json({ok:true,hierarchy:data.hierarchy})});
app.get('/api/admin/audit',async(req,res)=>{const c=await requirePerm(req,res,'view_audit');if(!c)return;res.json({audit:data.audit})});
app.get('/api/public/exams',(_q,res)=>res.json({exams:data.exams.filter(e=>e.active).map(e=>({...e,questions:publicQuestions(e.questions)}))}));
app.post('/api/exams/:id/submit',async(req,res)=>{const c=await current(req);if(!c.x)return res.status(401).json({error:'UNAUTHENTICATED'});const e=data.exams.find(x=>x.id===req.params.id&&x.active);if(!e)return res.status(404).json({error:'EXAM_NOT_FOUND'});const answers=req.body?.answers||{};let earned=0,total=0;for(const q of e.questions){const p=Number(q.points||1);total+=p;if(['choice','yesno'].includes(q.type)&&String(answers[q.id]??'')===String(q.correct??''))earned+=p}const score=total?Math.round(earned/total*100):0;const result={id:`result-${Date.now()}`,examId:e.id,userId:String(c.x.id),name:c.police?.name||c.x.global_name||c.x.username,score,passed:score>=e.passingScore,submittedAt:new Date().toISOString()};data.examResults.push(result);await saveData();res.json({ok:true,result})});
app.get('/auth/discord',(_q,res)=>{if(!DISCORD_CLIENT_ID||!DISCORD_CLIENT_SECRET)return res.status(503).send('Discord OAuth is not configured yet.');const p=new URLSearchParams({client_id:DISCORD_CLIENT_ID,response_type:'code',redirect_uri:DISCORD_REDIRECT_URI,scope:'identify'});res.redirect(`https://discord.com/oauth2/authorize?${p}`)});
app.get('/auth/discord/callback',async(req,res)=>{try{const code=String(req.query.code||'');if(!code)throw Error('Missing OAuth code');const body=new URLSearchParams({client_id:DISCORD_CLIENT_ID,client_secret:DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:DISCORD_REDIRECT_URI});const tr=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!tr.ok)throw Error('Discord token exchange failed');const tk=await tr.json();const mr=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${tk.access_token}`}});if(!mr.ok)throw Error('Discord identity lookup failed');const me=await mr.json();const token=jwt.sign({id:me.id,username:me.username,global_name:me.global_name,avatar:me.avatar},SESSION_SECRET,{expiresIn:'7d'});res.cookie('kayan_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.redirect(FRONTEND_URL||'/')}catch(e){res.status(500).send(`Discord login failed: ${e.message}`)}});
app.post('/api/logout',(_q,res)=>{res.clearCookie('kayan_session');res.json({ok:true})});
await loadData();
app.use(express.static(DIST_DIR,{index:'index.html'}));
app.use((req,res,next)=>{if(req.method!=='GET'||req.path.startsWith('/api/')||req.path.startsWith('/auth/'))return next();res.sendFile(path.join(DIST_DIR,'index.html'))});
app.listen(PORT,'0.0.0.0',()=>console.log(`Kayan Academy API: http://0.0.0.0:${PORT}`));
