import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, Users, ClipboardCheck, FileText, Shield, LogIn, Menu, X, ChevronLeft, Star, Settings, Network, LockKeyhole, Check, Power, UserCheck, Clock3, AlertCircle } from 'lucide-react';
import './academy-v2.css';

const logo = '/police-logo.png';
const ROLE = { officer:'ضابط', trainer:'مدرب', affairs:'الشؤون', academy_president:'رئيس الأكاديمية', academy_vice_president:'نائب رئيس الأكاديمية', academy_assistant_vice:'مساعد نائب الرئيس', police_commander:'قائد الشرطة' };
async function api(url, opts){ const r=await fetch(url,opts); let d={}; try{d=await r.json()}catch{} if(!r.ok) throw Error(d.error||'حدث خطأ في الطلب'); return d; }
const Page=({title,sub,children})=><><section className="pageTitle"><span>KAYAN POLICE ACADEMY</span><h1>{title}</h1><p>{sub}</p></section>{children}</>;

function App(){
 const [page,setPage]=useState('home'),[open,setOpen]=useState(false),[user,setUser]=useState(null),[hierarchy,setHierarchy]=useState([]);
 const go=p=>{setPage(p);setOpen(false)};
 useEffect(()=>{api('/api/me').then(setUser).catch(()=>setUser({authenticated:false}));api('/api/public/hierarchy').then(x=>setHierarchy(x.hierarchy||[])).catch(()=>{})},[]);
 const admin=!!user?.permissions?.isAdmin;
 const citizen=!!user?.authenticated&&!user?.permissions?.isOfficer;
 const nav=[['home','الرئيسية',LayoutDashboard],['hierarchy','هيكل الأكاديمية',Network],['applications','التقديمات',FileText]];
 if(user?.authenticated&&!citizen) nav.push(['exams','الاختبارات',ClipboardCheck],['members','أعضاء الأكاديمية',Users],['evaluations','التقييمات',Star]);
 if(admin) nav.push(['admin','مركز الإدارة',Settings]);
 const name=user?.police?.name||user?.discord?.global_name||'المستخدم';
 const rank=user?.police?.rank||ROLE[user?.role]||(admin?'إدارة الأكاديمية':'مواطن');
 return <div className="app"><aside className={open?'open':''}><div className="brand"><div className="logoFrame"><img src={logo} alt="شعار أكاديمية شرطة كيان"/></div><div><b>أكاديمية شرطة كيان</b><small>KAYAN POLICE ACADEMY</small></div></div><nav>{nav.map(([id,l,I])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><I size={18}/><span>{l}</span><ChevronLeft size={14}/></button>)}</nav><div className="sideBottom"><Shield size={17}/>البوابة الرسمية</div></aside><main><header><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div className="crumb">أكاديمية شرطة كيان <span>/</span>{nav.find(x=>x[0]===page)?.[1]}</div>{user?.authenticated?<div className="userHeader"><UserCheck size={16}/><b>{name}</b><span>{rank}</span>{admin&&<em>ADMIN</em>}<button onClick={async()=>{await api('/api/logout',{method:'POST'});location.reload()}}>خروج</button></div>:<button className="discord" onClick={()=>location.href='/auth/discord'}><LogIn size={17}/> تسجيل الدخول عبر Discord</button>}</header>{page==='home'?<Home user={user} go={go}/>:page==='hierarchy'?<Hierarchy data={hierarchy}/>:page==='applications'?<Applications user={user}/>:page==='exams'?<Exams/>:page==='members'?<Members/>:page==='evaluations'?<Evaluations/>:<Admin setHierarchy={setHierarchy}/>}</main></div>;
}
function Home({user,go}){return <><section className="hero"><div className="heroText"><small>OFFICIAL ACADEMY PORTAL</small><h1>أكاديمية<br/><strong>شرطة كيان</strong></h1><p>منصة موحدة للتقديم والقبول والتأهيل والاختبارات والسجل الأكاديمي.</p><div className="actions">{!user?.authenticated&&<button className="gold" onClick={()=>location.href='/auth/discord'}><LogIn size={17}/> تسجيل الدخول</button>}{user?.authenticated&&!user.permissions?.isOfficer&&<button className="gold" onClick={()=>go('applications')}><FileText size={17}/> التقديم للشرطة</button>}<button className="ghost" onClick={()=>go('hierarchy')}><Network size={17}/> هيكل الأكاديمية</button></div></div><div className="heroCrest"><img src={logo} alt="شعار الشرطة"/><b>KAYAN POLICE ACADEMY</b></div></section><section className="homeCards"><Info icon={Shield} title="بوابة رسمية" text="دخول موحد عبر Discord."/><Info icon={FileText} title="التقديمات" text="دفعات مستقلة وحالات قبول واضحة."/><Info icon={ClipboardCheck} title="الاختبارات" text="تصحيح تلقائي وحفظ النتائج."/><Info icon={UserCheck} title="السجل الأكاديمي" text="متابعة المتدربين والنتائج."/></section></>}
const Info=({icon:I,title,text})=><div className="info"><I/><div><b>{title}</b><span>{text}</span></div></div>;
function Hierarchy({data}){return <Page title="هيكل الأكاديمية" sub="القيادات والمناصب التي اختارت الإدارة إظهارها للعامة."><div className="hierarchyGrid">{data.map(x=><div className="hierCard" key={x.id}>{x.image?<img src={x.image} alt=""/>:<div className="placeholder"><Shield/></div>}<small>{x.title}</small><b>{x.name}</b></div>)}</div></Page>}
function Applications({user}){const[data,setData]=useState(null),[answers,setAnswers]=useState({}),[sent,setSent]=useState(false);useEffect(()=>{api('/api/public/academy').then(setData).catch(()=>{})},[]);if(!user?.authenticated)return <Page title="التقديمات" sub="سجّل الدخول عبر Discord للمتابعة."><div className="center panel"><LogIn/><h2>تسجيل الدخول مطلوب</h2><button className="gold" onClick={()=>location.href='/auth/discord'}>تسجيل الدخول</button></div></Page>;if(user.permissions?.isOfficer)return <Page title="التقديمات" sub="التقديم الإلكتروني مخصص للمواطنين المتقدمين."><div className="center panel"><LockKeyhole/><h2>هذه الصفحة ليست مخصصة لحسابك</h2></div></Page>;if(!data)return <Loading/>;if(!data.application?.enabled||!data.batch)return <Page title="التقديمات" sub="لا توجد دفعة مفتوحة حاليًا."><div className="closed panel"><Clock3/><h2>التقديمات مغلقة حاليًا</h2><p>سيظهر نموذج التقديم فور فتح دفعة جديدة من الإدارة.</p></div></Page>;if(sent)return <Page title="تم استلام طلبك" sub={`تم تسجيل طلبك ضمن دفعة «${data.batch.name}».`}><div className="success panel"><Check/><h2>تم إرسال التقديم بنجاح</h2><p>يمكن للإدارة الآن مراجعة طلبك وتحديد القرار.</p></div></Page>;const qs=data.application.questions||[];return <><Page title={data.batch.name} sub={data.application.description||'نموذج التقديم الرسمي.'}><div className="batchBanner"><div><span>الدفعة الحالية</span><b>{data.batch.name}</b></div><em>مفتوحة</em></div></Page><div className="form panel">{qs.map((q,i)=><Question key={q.id} q={q} n={i+1} value={answers[q.id]} onChange={v=>setAnswers(a=>({...a,[q.id]:v}))}/>}<button className="gold" onClick={async()=>{if(qs.some(q=>q.required&&String(answers[q.id]??'').trim()===''))return alert('أكمل الأسئلة المطلوبة');try{await api('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})});setSent(true)}catch(e){alert(e.message)}}}><Check size={17}/> إرسال التقديم</button></div></>}
function Question({q,n,value,onChange}){return <div className="question"><b>{n}. {q.text}</b>{q.type==='choice'&&<div className="options">{(q.options||[]).map(o=><label key={o}><input type="radio" name={q.id} checked={value===o} onChange={()=>onChange(o)}/>{o}</label>)}</div>}{q.type==='yesno'&&<div className="options"><label><input type="radio" name={q.id} checked={value==='نعم'} onChange={()=>onChange('نعم')}/>نعم</label><label><input type="radio" name={q.id} checked={value==='لا'} onChange={()=>onChange('لا')}/>لا</label></div>}{q.type==='text'&&<textarea value={value||''} onChange={e=>onChange(e.target.value)} placeholder="اكتب إجابتك..."/>}</div>}
function Exams(){return <Page title="الاختبارات" sub="الاختبارات المتاحة لك وفق المرحلة التدريبية."><div className="center panel"><ClipboardCheck/><h2>الاختبارات تدار من مركز الإدارة</h2><p>عند نشر اختبار سيظهر هنا للمستحقين مع التصحيح التلقائي.</p></div></Page>}
function Members(){const[members,setMembers]=useState([]);useEffect(()=>{api('/api/academy/members').then(x=>setMembers(x.members||[])).catch(()=>{})},[]);return <Page title="أعضاء الأكاديمية" sub="السجل الداخلي لأفراد الشرطة."><div className="panel table">{members.map(m=><div className="member" key={m.discordId}><div className="avatar">{m.name?.[0]||'؟'}</div><div><b>{m.name}</b><small>{m.rank||'بدون رتبة'} · {m.code||'بدون كود'}</small></div><span>{ROLE[m.role]||'ضابط'}</span></div>)}</div></Page>}
function Evaluations(){return <Page title="التقييمات" sub="متابعة الأداء الأكاديمي حسب الصلاحيات."><div className="center panel"><Star/><h2>التقييمات الأكاديمية</h2><p>سيتم عرض أدوات التقييم وفق صلاحيات الحساب.</p></div></Page>}
function Admin({setHierarchy}){const[state,setState]=useState(null),[tab,setTab]=useState('overview'),[msg,setMsg]=useState('');const load=()=>api('/api/admin/academy-state').then(setState).catch(e=>setMsg(e.message));useEffect(load,[]);if(!state)return <Loading/>;const refresh=()=>load();return <><section className="adminHero"><div><small>ACADEMY CONTROL CENTER</small><h1>مركز التحكم</h1><p>كل إدارة الأكاديمية من مكان واحد.</p></div><Settings size={42}/></section>{msg&&<div className="message"><AlertCircle size={16}/>{msg}</div>}<div className="tabs">{[['overview','نظرة عامة'],['applications','التقديمات والدفعات'],['questions','أسئلة التقديم'],['members','الأفراد والرتب'],['hierarchy','هيكل الأكاديمية']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</div>{tab==='overview'&&<Overview state={state}/>} {tab==='applications'&&<AdminApplications state={state} refresh={refresh}/>} {tab==='questions'&&<AdminQuestions application={state.application} refresh={refresh}/>} {tab==='members'&&<AdminMembers/>} {tab==='hierarchy'&&<AdminHierarchy data={state.hierarchy} save={async items=>{const d=await api('/api/admin/hierarchy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});setHierarchy(d.hierarchy||[]);setMsg('تم حفظ الهيكل');}}/>}</>}
function Overview({state}){const active=state.batches.find(x=>x.status==='open');return <div className="dashboard"><div className="dashCard"><FileText/><b>{state.batches.length}</b><span>دفعات</span></div><div className="dashCard"><UserCheck/><b>{state.applications.length}</b><span>طلبات</span></div><div className="dashCard"><Check/><b>{state.applications.filter(x=>x.status==='accepted').length}</b><span>مقبولين</span></div><div className="dashCard"><Power/><b>{active?'مفتوحة':'مغلقة'}</b><span>حالة التقديم</span></div><div className="panel wide"><h2>الدفعة الحالية</h2>{active?<div className="currentBatch"><div><small>مفتوحة الآن</small><b>{active.name}</b></div><span>{state.applications.filter(x=>x.batchId===active.id).length} طلب</span></div>:<p className="muted">لا توجد دفعة مفتوحة.</p>}</div></div>}
function AdminApplications({state,refresh}){const[batch,setBatch]=useState(''),[selected,setSelected]=useState(new Set()),[filter,setFilter]=useState('all');const active=state.batches.find(x=>x.status==='open');const apps=state.applications.filter(x=>filter==='all'||x.status===filter);const toggle=id=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});const create=async()=>{if(!batch.trim())return alert('اكتب اسم الدفعة');await api('/api/admin/batches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:batch.trim()})});setBatch('');refresh()};const close=async()=>{if(active)await api(`/api/admin/batches/${active.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'closed'})});refresh()};const decide=async status=>{await Promise.all([...selected].map(id=>api(`/api/admin/applications/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})})));setSelected(new Set());refresh()};return <div className="adminSection"><div className="toolbar"><input value={batch} onChange={e=>setBatch(e.target.value)} placeholder="اسم الدفعة الجديدة"/><button className="gold" onClick={create}>إنشاء دفعة</button>{active&&<button className="danger" onClick={close}>غلق الدفعة الحالية</button>}</div><div className="filters">{[['all','الكل'],['pending','قيد المراجعة'],['accepted','مقبول'],['rejected','مرفوض']].map(([v,l])=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} key={v}>{l}</button>)}<button disabled={!selected.size} onClick={()=>decide('accepted')}>قبول المحدد ({selected.size})</button><button disabled={!selected.size} onClick={()=>decide('rejected')}>رفض المحدد</button></div><div className="panel table">{apps.map(a=><label className="applicationRow" key={a.id}><input type="checkbox" checked={selected.has(a.id)} onChange={()=>toggle(a.id)}/><div><b>{a.name||a.discordId}</b><small>{a.discordId} · {a.batchName||a.batchId}</small></div><span className={`status ${a.status}`}>{a.status==='accepted'?'مقبول':a.status==='rejected'?'مرفوض':'قيد المراجعة'}</span></label>)}{!apps.length&&<div className="empty">لا توجد طلبات بهذه الحالة.</div>}</div></div>}
function AdminQuestions({application,refresh}){const[q,setQ]=useState({text:'',type:'choice',required:true,options:['نعم','لا']});const add=async()=>{if(!q.text.trim())return alert('اكتب السؤال');await api('/api/admin/application-questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(q)});setQ({text:'',type:'choice',required:true,options:['نعم','لا']});refresh()};return <div className="panel form"><h2>إدارة أسئلة التقديم</h2><input value={q.text} onChange={e=>setQ({...q,text:e.target.value})} placeholder="نص السؤال"/><select value={q.type} onChange={e=>setQ({...q,type:e.target.value})}><option value="choice">اختيار من متعدد</option><option value="yesno">نعم / لا</option><option value="text">إجابة نصية</option></select><button className="gold" onClick={add}>إضافة السؤال</button></div>}
function AdminMembers(){return <Page title="الأفراد والرتب" sub="إدارة أفراد الأكاديمية وصلاحياتهم."><div className="center panel"><Users/><h2>إدارة الأفراد</h2><p>تُدار بيانات الأفراد من واجهة الصلاحيات المخصصة.</p></div></Page>}
function AdminHierarchy({data,save}){const[items,setItems]=useState(data||[]);const add=()=>setItems([...items,{id:Date.now().toString(),title:'منصب',name:'اسم الشخص',image:''}]);return <div className="panel"><div className="toolbar"><h2>هيكل الأكاديمية</h2><button className="gold" onClick={add}>إضافة شخص</button><button onClick={()=>save(items)}>حفظ</button></div>{items.map((x,i)=><div className="hierEdit" key={x.id}><input value={x.title} onChange={e=>setItems(items.map((a,j)=>j===i?{...a,title:e.target.value}:a))}/><input value={x.name} onChange={e=>setItems(items.map((a,j)=>j===i?{...a,name:e.target.value}:a))}/><input value={x.image||''} onChange={e=>setItems(items.map((a,j)=>j===i?{...a,image:e.target.value}:a))}/></div>)}</div>}
function Loading(){return <div className="center panel"><Clock3/><h2>جاري التحميل...</h2></div>}

createRoot(document.getElementById('root')).render(<App/>);
