import React, { useEffect, useState } from 'react';
import { LayoutDashboard, ClipboardCheck, FileText, Shield, LogIn, Menu, X, ChevronLeft, Star, Settings, Network, UserCog, Upload, Save, Search, LockKeyhole, Plus, Trash2, Check, Play } from 'lucide-react';
import './styles.css';

// Official local academy logo. Keep the original PNG untouched.
const logo = '/police-logo.png';
const ROLE = { officer: 'ضابط', trainer: 'مدرب', affairs: 'الشؤون', academy_president: 'رئيس الأكاديمية', academy_vice_president: 'نائب رئيس الأكاديمية', academy_assistant_vice: 'مساعد نائب الرئيس', police_commander: 'قائد الشرطة' };
async function api(url, options) { const r = await fetch(url, options); let d = {}; try { d = await r.json(); } catch (_) {} if (!r.ok) throw new Error(d.error || 'حدث خطأ'); return d; }
const Page = ({ title, sub, children }) => <><section className="pageTitle"><span className="eyebrow">KAYAN POLICE ACADEMY</span><h1>{title}</h1><p>{sub}</p></section>{children}</>;
function App() {
  const [page, setPage] = useState('home'), [open, setOpen] = useState(false), [user, setUser] = useState(null), [hierarchy, setHierarchy] = useState([]);
  const go = p => { setPage(p); setOpen(false); };
  useEffect(() => { api('/api/me').then(setUser).catch(() => setUser({ authenticated: false })); api('/api/public/hierarchy').then(d => setHierarchy(d.hierarchy || [])).catch(() => {}); }, []);
  const nav = [['home','الرئيسية',LayoutDashboard],['hierarchy','هيكل الأكاديمية',Network]];
  if (user?.authenticated && user.permissions?.isCitizen) nav.push(['applications','التقديمات',FileText]);
  if (user?.authenticated && !user.permissions?.isCitizen) nav.push(['exams','الاختبارات',ClipboardCheck],['evaluations','التقييمات',Star]);
  if (user?.permissions?.isAdmin) nav.push(['admin','مركز الإدارة',Settings]);
  return <div className="app"><aside className={open ? 'open' : ''}><div className="brand"><div className="logoFrame"><img src={logo} alt="شعار شرطة كيان" /></div><div><b>أكاديمية شرطة كيان</b><small>KAYAN POLICE ACADEMY</small></div></div><nav>{nav.map(([id,label,I]) => <button className={page === id ? 'active' : ''} onClick={() => go(id)} key={id}><I size={18}/>{label}<ChevronLeft size={14}/></button>)}</nav><div className="sideBottom"><Shield size={17}/>البوابة الرسمية</div></aside><main><header><button className="menu" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button><div className="crumb">أكاديمية شرطة كيان <span>/</span>{nav.find(x => x[0] === page)?.[1]}</div>{user?.authenticated ? <div className="userHeader"><span>{user.police?.name || user.discord?.global_name || 'المستخدم'}</span><span className="rolePill">{user.police?.rank || ROLE[user.role] || 'مواطن'}</span>{user.permissions?.isAdmin && <span className="adminTag">ADMIN</span>}<button className="textBtn" onClick={async () => { await api('/api/logout',{method:'POST'}); location.reload(); }}>خروج</button></div> : <button className="discord" onClick={() => location.href='/auth/discord'}><LogIn size={17}/> تسجيل الدخول</button>}</header>{page === 'home' ? <Home user={user} go={go}/> : page === 'hierarchy' ? <Hierarchy data={hierarchy}/> : page === 'applications' ? <Applications user={user}/> : page === 'exams' ? <Exams user={user}/> : page === 'evaluations' ? <Evaluations/> : <Admin user={user} setHierarchy={setHierarchy}/>}</main></div>;
}
function Home({user,go}) { return <section className="welcome"><div className="welcomeCopy"><span className="eyebrow">KAYAN POLICE ACADEMY</span><h1>مرحبًا بك في<br/><strong>أكاديمية شرطة كيان</strong></h1><p>البوابة الرسمية للتقديم والتأهيل والاختبارات والسجل الأكاديمي.</p><div className="actions">{!user?.authenticated && <button className="primary" onClick={() => location.href='/auth/discord'}><LogIn size={17}/> تسجيل الدخول</button>}{user?.permissions?.isCitizen && <button className="primary" onClick={() => go('applications')}>التقديم للشرطة <ChevronLeft size={17}/></button>}<button className="secondary dark" onClick={() => go('hierarchy')}>هيكل الأكاديمية <Network size={17}/></button></div></div><div className="crestCard"><div className="crestGlow"/><img src={logo} alt="شعار شرطة كيان"/><span>أكاديمية شرطة كيان</span></div></section>; }
function Hierarchy({data}) { return <Page title="هيكل الأكاديمية" sub="القيادات والمناصب المعتمدة داخل الأكاديمية."><div className="hierarchyGrid">{data.map(x => <div className="hierCard" key={x.id}>{x.image ? <img src={x.image} alt=""/> : <div className="hierPlaceholder"><Shield size={36}/></div>}<div className="hierInfo"><span>{x.title}</span><b>{x.name}</b></div></div>)}</div></Page>; }
function Applications({user}) { const [data,setData]=useState(null),[answers,setAnswers]=useState({}),[sent,setSent]=useState(false); useEffect(()=>{api('/api/public/application').then(d=>setData(d.application)).catch(()=>{});},[]); if(!user?.authenticated||!user.permissions?.isCitizen)return <Restricted/>; if(!data)return <Page title="التقديم" sub="جاري تحميل النموذج..."/>; if(sent)return <Page title="تم استلام التقديم" sub="تم إرسال طلبك إلى الأكاديمية للمراجعة."><div className="panel success"><Check/><h2>تم إرسال الطلب بنجاح</h2></div></Page>; return <><Page title={data.title} sub={data.description}/><div className="formPanel"><div className="formTop"><span>نموذج التقديم</span><b>النجاح {data.passingScore}%</b></div>{data.questions?.length ? data.questions.map((q,i)=><Question key={q.id} q={q} n={i+1} value={answers[q.id]} onChange={v=>setAnswers(a=>({...a,[q.id]:v}))}/>) : <div className="empty"><FileText/><h2>لم يتم فتح نموذج التقديم بعد</h2></div>}{data.questions?.length>0&&<button className="primary" onClick={()=>{if(data.questions.some(q=>q.required&&String(answers[q.id]??'').trim()===''))return alert('أكمل الأسئلة المطلوبة');setSent(true);}}>إرسال التقديم <ChevronLeft size={16}/></button>}</div></>; }
function Exams({user}) { const [exams,setExams]=useState([]),[active,setActive]=useState(null),[answers,setAnswers]=useState({}),[result,setResult]=useState(null); useEffect(()=>{api('/api/public/exams').then(d=>setExams(d.exams||[])).catch(()=>{});},[]); if(!user?.authenticated||user.permissions?.isCitizen)return <Restricted/>; if(result)return <Page title="نتيجة الاختبار" sub="تم التصحيح تلقائيًا."><div className="result"><b>{result.score}%</b><span>{result.passed?'ناجح':'غير مجتاز'}</span></div></Page>; if(active)return <><Page title={active.title} sub={`المدة ${active.duration} دقيقة · النجاح ${active.passingScore}%`}/><div className="formPanel">{active.questions.map((q,i)=><Question key={q.id} q={q} n={i+1} value={answers[q.id]} onChange={v=>setAnswers(a=>({...a,[q.id]:v}))}/>)}<button className="primary" onClick={async()=>{try{const d=await api(`/api/exams/${active.id}/submit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})});setResult(d.result);}catch(e){alert(e.message);}}}>إنهاء وتصحيح الاختبار <Check size={16}/></button></div></>; return <><Page title="الاختبارات" sub="الاختبارات المتاحة لك وفق مرحلتك التدريبية."/><div className="examGrid">{exams.map(e=><div className="panel exam" key={e.id}><div className="examIcon"><ClipboardCheck/></div><h2>{e.title}</h2><p>{e.questions.length} سؤال · {e.duration} دقيقة · النجاح {e.passingScore}%</p><button className="primary" onClick={()=>{setActive(e);setAnswers({});}}><Play size={15}/> بدء الاختبار</button></div>)}</div>{!exams.length&&<div className="panel empty"><ClipboardCheck/><h2>لا توجد اختبارات متاحة حاليًا</h2></div>}</>; }
function Question({q,n,value,onChange}) { return <div className="question"><b>{n}. {q.text}</b>{q.type==='choice'&&<div className="options">{q.options.map(o=><label key={o}><input type="radio" name={q.id} checked={value===o} onChange={()=>onChange(o)}/>{o}</label>)}</div>}{q.type==='yesno'&&<div className="options"><label><input type="radio" name={q.id} checked={value==='نعم'} onChange={()=>onChange('نعم')}/>نعم</label><label><input type="radio" name={q.id} checked={value==='لا'} onChange={()=>onChange('لا')}/>لا</label></div>}{q.type==='text'&&<textarea value={value||''} onChange={e=>onChange(e.target.value)} placeholder="اكتب إجابتك..."/>}</div>; }
function Evaluations() { return <Page title="التقييمات" sub="متابعة الأداء الأكاديمي وفق الصلاحيات الممنوحة."><div className="cards"><div className="metric"><Star/><b>تقييمات المستجدين</b><span>متاحة للقيادات والشؤون.</span></div><div className="metric"><Star/><b>تقييم المدربين</b><span>تقييم متبادل داخل الأكاديمية.</span></div></div></Page>; }
function Admin({user,setHierarchy}) { const [tab,setTab]=useState('overview'),[state,setState]=useState(null),[content,setContent]=useState(null),[msg,setMsg]=useState(''); const load=async()=>{try{setState(await api('/api/admin/state'));setContent(await api('/api/admin/academy-content'));}catch(e){setMsg(e.message);}}; useEffect(()=>{if(user?.permissions?.isAdmin)load();},[user]); if(!user?.permissions?.isAdmin)return <Restricted/>; if(!state||!content)return <Page title="مركز الإدارة" sub="جاري تحميل مركز التحكم..."/>; const can=p=>user.permissions?.adminPermissions?.includes(p); return <><section className="adminHero"><div><span className="eyebrow">KAYAN ADMINISTRATION</span><h1>مركز التحكم</h1><p>إدارة الأفراد والرتب وهيكل الأكاديمية والتقديمات والاختبارات.</p></div><UserCog size={48}/></section>{msg&&<div className="adminMessage">{msg}</div>}<div className="adminTabs">{[['overview','نظرة عامة'],['members','الأفراد والرتب'],['hierarchy','هيكل الأكاديمية'],['applications','التقديمات'],['exams','الاختبارات']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</div>{tab==='overview'&&<div className="adminCards"><div className="panel"><b className="big">{state.members?.length||0}</b><span>أفراد</span></div><div className="panel"><b className="big">{state.admins?.length||0}</b><span>أدمن</span></div><div className="panel"><b className="big">{content.exams?.length||0}</b><span>اختبارات</span></div><div className="panel"><b className="big">{content.application?.questions?.length||0}</b><span>أسئلة التقديم</span></div></div>}{tab==='members'&&<AdminMembers state={state} load={load} can={can}/>} {tab==='hierarchy'&&<AdminHierarchy state={state} setState={setState} save={async items=>{try{const d=await api('/api/admin/hierarchy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});setHierarchy(d.hierarchy||[]);setState(s=>({...s,hierarchy:d.hierarchy||[]}));setMsg('تم حفظ الهيكل');}catch(e){setMsg(e.message);}}}/>} {tab==='applications'&&<AdminApplications data={content.application} refresh={load}/>} {tab==='exams'&&<AdminExams data={content.exams||[]} refresh={load}/>}</>; }
function AdminMembers({state,load,can}) { const [q,setQ]=useState(''); const list=(state.members||[]).filter(m=>`${m.name||''} ${m.discordId||''} ${m.rank||''}`.toLowerCase().includes(q.toLowerCase())); return <div className="panel table"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث بالاسم أو Discord ID"/></div>{list.map(m=><div className="row" key={m.discordId}><div className="avatar">{m.name?.[0]||'؟'}</div><div className="person"><b>{m.name||'غير مسجل'}</b><small>{m.rank||'بدون رتبة'} · {m.discordId}</small></div>{can('manage_roles')?<select value={m.role||'officer'} onChange={async e=>{await api('/api/admin/role',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({discordId:m.discordId,role:e.target.value})});load();}}>{Object.entries(ROLE).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<span className="rolePill">{ROLE[m.role]||'ضابط'}</span>}</div>)}</div>; }
function AdminHierarchy({state,setState,save}) { const add=()=>setState(s=>({...s,hierarchy:[...(s.hierarchy||[]),{id:`new-${Date.now()}`,title:'منصب جديد',name:'',discordId:'',image:''}]})); const update=(i,k,v)=>setState(s=>({...s,hierarchy:s.hierarchy.map((x,j)=>j===i?{...x,[k]:v}:x)})); return <div className="adminManager"><div className="panelHead"><h2>هيكل الأكاديمية</h2><button className="secondary" onClick={add}><Plus size={14}/> إضافة منصب</button></div><div className="hierAdmin">{(state.hierarchy||[]).map((x,i)=><div className="hierEdit" key={x.id}><div className="preview">{x.image?<img src={x.image} alt=""/>:<Shield/>}</div><div className="editFields"><input value={x.title} onChange={e=>update(i,'title',e.target.value)} placeholder="المنصب"/><input value={x.name} onChange={e=>update(i,'name',e.target.value)} placeholder="الاسم"/><input value={x.discordId||''} onChange={e=>update(i,'discordId',e.target.value)} placeholder="Discord ID"/><label className="upload"><Upload size={13}/> صورة PNG<input type="file" accept="image/png" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>update(i,'image',String(r.result));r.readAsDataURL(f);}}/></label></div><button className="danger" onClick={()=>setState(s=>({...s,hierarchy:s.hierarchy.filter((_,j)=>j!==i)}))}><Trash2 size={14}/></button></div>)}</div><button className="primary" onClick={()=>save(state.hierarchy||[])}><Save size={14}/> حفظ الهيكل</button></div>; }
function AdminApplications({data,refresh}) { return <div className="adminManager"><div className="panel"><h2>{data?.title||'التقديمات'}</h2><p className="muted">يمكن إدارة نموذج التقديم من لوحة الإدارة.</p><div className="questionList">{(data?.questions||[]).map((q,i)=><div className="questionAdmin" key={q.id}><b>{i+1}. {q.text}</b><small>{q.type} · {q.points} درجة</small></div>)}</div></div></div>; }
function AdminExams({data,refresh}) { return <div className="adminManager"><div className="panel"><h2>الاختبارات</h2><p className="muted">إدارة الاختبارات المتاحة للمستجدين والضباط.</p><div className="questionList">{data.map(e=><div className="questionAdmin" key={e.id}><b>{e.title}</b><small>{e.questions?.length||0} سؤال · {e.passingScore}% للنجاح</small></div>)}</div></div></div>; }
function Restricted(){return <Page title="غير متاح" sub="هذه الصفحة تتطلب صلاحية مختلفة."/>}
createRoot(document.getElementById('root')).render(<App/>);
