begin;

alter table public.exam_attempts
  add column if not exists answers_updated_at timestamptz not null default now(),
  add column if not exists answers_revision bigint not null default 0;

create index if not exists exam_attempts_answers_updated_idx
  on public.exam_attempts(exam_id, discord_id, answers_updated_at desc);

create table if not exists public.attempt_answers (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid not null references public.exam_attempts(id) on delete cascade,
  question_id uuid not null references public.exam_questions(id) on delete restrict,
  answer jsonb not null,
  revision bigint not null default 0,
  client_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (attempt_id, question_id)
);
create index if not exists attempt_answers_attempt_idx on public.attempt_answers(attempt_id);

create table if not exists public.exam_events (
  id bigint generated by default as identity primary key,
  attempt_id uuid references public.exam_attempts(id) on delete set null,
  exam_id uuid references public.exams(id) on delete set null,
  discord_id text,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists exam_events_attempt_idx on public.exam_events(attempt_id, created_at desc);
create index if not exists exam_events_created_idx on public.exam_events(created_at desc);

create or replace function public.save_exam_attempt_answers(
  p_legacy_id text,
  p_answers jsonb,
  p_answers_updated_at timestamptz,
  p_status text default 'in_progress'
)
returns table(id uuid, legacy_id text, exam_id uuid, discord_id text, started_at timestamptz, expires_at timestamptz, submitted_at timestamptz, resume_at timestamptz, resume_until timestamptz, resume_duration_minutes integer, answers jsonb, question_order uuid[], status text, auto_submitted boolean, created_at timestamptz, updated_at timestamptz, answers_updated_at timestamptz, answers_revision bigint)
language plpgsql security definer set search_path = public
as $$
declare v_id uuid; v_current_updated timestamptz; v_current_status text; v_revision bigint; v_incoming timestamptz := coalesce(p_answers_updated_at, now()); v_new_status text := coalesce(p_status,'in_progress');
begin
  select a.id,a.answers_updated_at,a.status,a.answers_revision into v_id,v_current_updated,v_current_status,v_revision from public.exam_attempts a where a.legacy_id=p_legacy_id for update;
  if not found then raise exception 'EXAM_ATTEMPT_NOT_FOUND' using errcode='P0002'; end if;
  if v_current_status='submitted' then
    return query select a.id,a.legacy_id,a.exam_id,a.discord_id,a.started_at,a.expires_at,a.submitted_at,a.resume_at,a.resume_until,a.resume_duration_minutes,a.answers,a.question_order,a.status,a.auto_submitted,a.created_at,a.updated_at,a.answers_updated_at,a.answers_revision from public.exam_attempts a where a.id=v_id; return;
  end if;
  if v_current_updated is null or v_incoming>=v_current_updated then
    update public.exam_attempts a set answers=coalesce(p_answers,a.answers),answers_updated_at=v_incoming,answers_revision=greatest(coalesce(a.answers_revision,0)+1,coalesce(v_revision,0)+1),status=case when v_new_status='submitted' then 'submitted' else coalesce(a.status,'in_progress') end,submitted_at=case when v_new_status='submitted' and a.submitted_at is null then now() else a.submitted_at end,updated_at=now() where a.id=v_id;
  end if;
  return query select a.id,a.legacy_id,a.exam_id,a.discord_id,a.started_at,a.expires_at,a.submitted_at,a.resume_at,a.resume_until,a.resume_duration_minutes,a.answers,a.question_order,a.status,a.auto_submitted,a.created_at,a.updated_at,a.answers_updated_at,a.answers_revision from public.exam_attempts a where a.id=v_id;
end;
$$;

create or replace function public.save_exam_attempt_answer(p_attempt_id uuid,p_discord_id text,p_question_id uuid,p_answer jsonb,p_client_revision bigint default 0,p_client_updated_at timestamptz default null)
returns table(saved boolean,revision bigint,server_updated_at timestamptz)
language plpgsql security definer set search_path=public
as $$
declare v_status text; v_revision bigint; v_updated timestamptz; v_exam_id uuid;
begin
  select status,answers_revision,answers_updated_at,exam_id into v_status,v_revision,v_updated,v_exam_id from public.exam_attempts where id=p_attempt_id and discord_id=p_discord_id for update;
  if not found then raise exception 'ATTEMPT_NOT_FOUND_OR_NOT_OWNED' using errcode='P0002'; end if;
  if v_status<>'in_progress' then raise exception 'ATTEMPT_NOT_EDITABLE' using errcode='P0003'; end if;
  v_revision:=greatest(coalesce(v_revision,0)+1,coalesce(p_client_revision,0)); v_updated:=now();
  insert into public.attempt_answers(attempt_id,question_id,answer,revision,client_updated_at,updated_at) values(p_attempt_id,p_question_id,p_answer,v_revision,p_client_updated_at,v_updated)
  on conflict(attempt_id,question_id) do update set answer=excluded.answer,revision=excluded.revision,client_updated_at=excluded.client_updated_at,updated_at=excluded.updated_at where public.attempt_answers.revision<=excluded.revision;
  update public.exam_attempts set answers_revision=v_revision,answers_updated_at=v_updated,updated_at=now() where id=p_attempt_id;
  insert into public.exam_events(attempt_id,exam_id,discord_id,event_type,metadata) values(p_attempt_id,v_exam_id,p_discord_id,'ANSWER_SAVED',jsonb_build_object('question_id',p_question_id,'revision',v_revision));
  return query select true,v_revision,v_updated;
end;
$$;

create or replace function public.submit_exam_attempt(p_attempt_id uuid,p_discord_id text,p_auto_submitted boolean default false)
returns table(submitted boolean,status text,submitted_at timestamptz)
language plpgsql security definer set search_path=public
as $$
declare v_status text; v_exam_id uuid; v_submitted_at timestamptz;
begin
  select status,exam_id,exam_attempts.submitted_at into v_status,v_exam_id,v_submitted_at from public.exam_attempts where id=p_attempt_id and discord_id=p_discord_id for update;
  if not found then raise exception 'ATTEMPT_NOT_FOUND_OR_NOT_OWNED' using errcode='P0002'; end if;
  if v_status='submitted' then return query select true,v_status,v_submitted_at; return; end if;
  if v_status<>'in_progress' then raise exception 'ATTEMPT_NOT_SUBMITTABLE' using errcode='P0003'; end if;
  v_submitted_at:=now(); update public.exam_attempts set status='submitted',submitted_at=v_submitted_at,auto_submitted=p_auto_submitted,updated_at=now() where id=p_attempt_id;
  insert into public.exam_events(attempt_id,exam_id,discord_id,event_type,metadata) values(p_attempt_id,v_exam_id,p_discord_id,case when p_auto_submitted then 'EXAM_AUTO_SUBMITTED' else 'EXAM_SUBMIT_SUCCESS' end,'{}'::jsonb);
  return query select true,'submitted'::text,v_submitted_at;
end;
$$;

revoke all on function public.save_exam_attempt_answers(text,jsonb,timestamptz,text) from public;
revoke all on function public.save_exam_attempt_answer(uuid,text,uuid,jsonb,bigint,timestamptz) from public;
revoke all on function public.submit_exam_attempt(uuid,text,boolean) from public;
grant execute on function public.save_exam_attempt_answers(text,jsonb,timestamptz,text) to service_role;
grant execute on function public.save_exam_attempt_answer(uuid,text,uuid,jsonb,bigint,timestamptz) to service_role;
grant execute on function public.submit_exam_attempt(uuid,text,boolean) to service_role;

commit;
